const data = {
  "base": {
    "Stand LP": [{c:4}, {hap:2}, {pc:7}],
    "Stand MP": [{c:5}, {hap:5}, {pc:16}],
    "Stand HP": [{c:11}, {hap:3}, {pc:21}],
    "Stand LK": [{c:3}, {hap:3}, {pc:12}],
    "Stand MK": [{c:7}, {hap:3}, {pc:17}],
    "Stand HK": [{c:8}, {hap:4}, {pc:19}],
    "Crouch LP": [{c:3}, {hap:2}, {pc:9}],
    "Crouch MP": [{c:7}, {hap:3}, {pc:18}],
    "Crouch HP": [{c:9}, {hap:3}, {pc:28}],
    "Crouch LK": [{c:4}, {hap:3}, {pc:8}],
    "Crouch MK": [{c:6}, {hap:3}, {pc:16}],
    "Crouch HK": [{c:9}, {hap:6}, {pc:20}],
    "Jump LP": [{c:4}, {hap:9}],
    "Jump MP": [{c:6}, {hap:4}],
    "Jump HP": [{c:10}, {hap:6}],
    "Jump LK": [{c:4}, {hap:6}],
    "Jump MK": [{c:6}, {hap:6}],
    "Jump HK": [{c:7}, {hap:8}],
    "Gong Fu": [{c:8}, {hap:5}],
    "Pu Lao": [{c:23}, {hap:3}, {pc:18}],
    "Chi Wen": [{c:15}, {hap:3}, {pc:21}],
    "Qiu Niu": [{c:13}, {hap:3}, {pc:5}, {hap:3}, {pc:24}],
    "Hun Dun": [{c:4}, {hap:2}, {pc:1}, {c:7}, {hap:2}, {pc:16}],
    "Qiong Qi": [{c:11}, {hap:1}, {c:13}, {hap:3}, {pc:29}],
    "Whisper": [{c:5}, {hap:3}, {pc:23}],
    "Gluttony": [{c:5}, {hap:3}, {pc:23}],
    "Drive Impact: Zao Chi": [{pcat:25}, {hap:2}, {pc:35}],
    "Drive Reversal: Feng Shi": [{ip:19}, {hap:3}, {pc:31}],
    "Drive Parry": [{pcat:12}, {pc:33}],
    "Drive Rush": [{c:45}],
    "Taunt": [],
    "Sinister Slide": [{c:216}],
    "Sinister Slide > Heel Strike": [{c:21}, {hap:3}, {pc:9}, {hap:3}, {pc:20}],
    "Sinister Slide > Venomous Fang": [{c:29}, {hap:15}, {pc:30}],
    "Sinister Slide > Entrapment": [{c:33}, {hap:3}, {pc:55}],
    "Sinister Slide > Exit": [{c:49}],
    "Nightshade Pulse": [{c:16}, {pat:36}],
    "Nightshade Chaser": [{c:16}, {pat:14}, {pc:12}, {pat:2}, {pc:34}],
    "Nightshade Chase (Bubble Burst)": [],
    "OD Nightshade Pulse": [{c:15}, {pat:29}],
    "OD Nightshade Chaser": [{c:15}, {pat:29}, {pc:12}, {pat:5}, {pc:28}],
    "OD Nightshade Chaser (Bubble Burst)": [],
    "Orchid Spring": [{c:46}],
    "Toxic Wreath": [{c:12}, {hap:3}, {c:14}, {hap:9}, {pc:13}],
    "LP Serpent Lash": [{c:13}, {hap:3}, {pc:26}],
    "MP Serpent Lash": [{c:16}, {hap:6}, {pc:24}],
    "HP Serpent Lash": [{c:10}, {hap:6}, {pc:32}],
    "OD Serpent Lash": [{c:21}, {hap:5}, {pc:25}],
    "LK Cruel Fate": [{c:23}, {hap:2}, {pc:5}, {hap:2}, {pc:4}, {hap:2}, {pc:5}, {hap:2}, {pc:18}],
    "MK Cruel Fate": [{c:27}, {hap:2}, {pc:5}, {hap:2}, {pc:4}, {hap:2}, {pc:5}, {hap:2}, {pc:18}],
    "HK Cruel Fate": [{c:32}, {hap:2}, {pc:5}, {hap:2}, {pc:4}, {hap:2}, {pc:5}, {hap:2}, {pc:18}],
    "OD Cruel Fate": [{c:28}, {hap:2}, {pc:4}, {hap:2}, {pc:4}, {hap:2}, {pc:5}, {hap:2}, {pc:18}],
    "LK Snake Step": [{c:37}],
    "MK Snake Step": [{c:39}],
    "HK Snake Step": [{c:50}],
    "OD Snake Step": [{psip:48}],
    "Deadly Implication": [{sip:9}, {hap:3}, {pc:68}],
    "Tainted Talons": [{c:6}, {pat:53}, {pc:28}, {pat:12}, {pc:24}],
    "Claws of Ya Zi": [{ip:9}, {hap:3}, {pc:58}],
    "Claws of Ya Zi (Critical Art)": [{ip:9}, {hap:3}, {pc:58}]
  }
}
export default data;