const data = {
  "base": {
    "Stand LP": [{c:3}, {hap:3}, {pc:7}],
    "Stand MP": [{c:5}, {hap:4}, {pc:11}],
    "Stand HP": [{c:8}, {hap:5}, {pc:18}],
    "Stand LK": [{c:4}, {hap:3}, {pc:11}],
    "Stand MK": [{c:6}, {hap:5}, {pc:15}],
    "Stand HK": [{c:12}, {hap:3}, {pc:8}, {hap:4}, {pc:16}],
    "Crouch LP": [{c:3}, {hap:2}, {pc:9}],
    "Crouch MP": [{c:5}, {hap:3}, {pc:14}],
    "Crouch HP": [{c:7}, {hap:8}, {pc:19}],
    "Crouch LK": [{c:4}, {hap:2}, {pc:10}],
    "Crouch MK": [{c:7}, {hap:3}, {pc:19}],
    "Crouch HK": [{c:8}, {hap:3}, {pc:23}],
    "Jump LP": [{c:3}, {hap:10}],
    "Jump MP": [{c:7}, {hap:4}],
    "Jump HP": [{c:8}, {hap:6}],
    "Jump LK": [{c:5}, {hap:10}],
    "Jump MK": [{c:6}, {hap:6}],
    "Jump HK": [{c:11}, {hap:6}],
    "Tenmaku Blade Kick": [{hap:15}, {pc:13}],
    "Skull Splitter": [{c:19}, {hap:1}, {pc:1}, {hap:3}, {pc:18}],
    "Resso Snap Kick": [{c:9}, {hap:3}, {pc:18}],
    "Kikoku": [{c:12}, {hap:4}, {pc:20}],
    "Rago High Kick": [{c:11}, {hap:5}, {pc:27}],
    "Viscera Piercer": [{c:5}, {hap:4}, {c:6}, {hap:3}, {pc:21}],
    "Bone Crusher Axe Kick": [{c:6}, {hap:2}, {c:19}, {hap:3}, {pc:20}],
    "Kikoku Combination 1": [{c:12}, {hap:4}, {c:10}, {hap:3}, {pc:21}],
    "Kikoku Combination 2": [{c:12}, {hap:4}, {c:10}, {hap:3}, {pc:8}, {hap:3}, {pc:21}],
    "Goshoha": [{c:5}, {hap:3}, {pc:23}],
    "Shuretto": [{c:5}, {hap:3}, {pc:23}],
    "Drive Impact: Oni Goroshi": [{c:25}, {hap:2}, {pc:32}],
    "Drive Reversal: Souha Double Palm": [{c:19}, {hap:3}, {pc:31}],
    "Drive Parry": [{c:45}],
    "Drive Rush": [{c:45}],
    "Taunt": [],
    "LP Gou Hadoken": [{c:15}, {pat:31}],
    "MP Gou Hadoken": [{c:15}, {pat:33}],
    "HP Gou Hadoken": [{c:15}, {pat:35}],
    "Gou Hadoken (lvl 2)": [{c:30}, {pat:30}],
    "Gou Hadoken (lvl 3)": [{c:55}, {pat:29}],
    "OD Gou Hadoken": [{c:11}, {pat:30}],
    "OD Gou Hadoken (hold)": [{c:30}, {pat:29}],
    "LP Zanku Hadoken": [{c:12}, {pat:35}],
    "MP Zanku Hadoken": [{c:12}, {pat:35}],
    "HP Zanku Hadoken": [{c:12}, {pat:35}],
    "OD Zanku Hadoken": [{c:5}, {pat:49}, {pc:1}],
    "LP Gou Shoryuken": [{c:4}, {hap:10}, {pc:33}],
    "MP Gou Shoryuken": [{c:5}, {hap:10}, {pc:42}],
    "HP Gou Shoryuken": [{c:6}, {hap:11}, {pc:50}],
    "OD Gou Shoryuken": [{c:5}, {hap:11}, {pc:52}],
    "LP Adamant Flame": [{c:14}, {hap:3}, {pc:23}],
    "LP Adamant Flame follow-up": [{c:14}, {hap:3}, {pc:8}, {hap:4}, {pc:18}],
    "MP Adamant Flame": [{c:18}, {hap:3}, {pc:23}],
    "MP Adamant Flame follow-up": [{c:18}, {hap:3}, {pc:8}, {hap:4}, {pc:32}],
    "HP Adamant Flame": [{c:22}, {hap:3}, {pc:21}],
    "HP Adamant Flame follow-up": [{c:18}, {hap:3}, {pc:12}, {hap:4}, {pc:28}],
    "OD Adamant Flame": [{c:18}, {hap:3}, {pc:22}],
    "OD Adamant Flame follow-up": [{c:18}, {hap:3}, {pc:8}, {hap:4}, {pc:4}, {hap:3}, {pc:25}],
    "LK Tatsumaki Zanku-kyaku": [{c:11}, {hap:2}, {pc:27}],
    "MK Tatsumaki Zanku-kyaku": [{c:10}, {hap:2}, {pc:13}, {hap:2}, {pc:31}],
    "HK Tatsumaki Zanku-kyaku": [{c:6}, {hap:3}, {pc:6}, {hap:3}, {pc:9}, {hap:3}, {pc:18}, {hap:3}, {pc:41}],
    "OD Tatsumaki Zanku-kyaku": [{c:12}, {hap:2}, {pc:4}, {hap:2}, {pc:4}, {hap:2}, {pc:3}, {hap:2}, {pc:4}, {hap:2}, {pc:26}],
    "Aerial Tatsumaki Zanku-kyaku": [{c:10}, {hap:2}, {pc:5}, {hap:2}, {pc:5}, {hap:5}],
    "OD Aerial Tatsumaki Zanku-kyaku": [{c:10}, {hap:2}, {pc:1}, {hap:3}, {pc:1}, {hap:3}, {pc:1}, {hap:3}, {pc:2}, {hap:2}],
    "Demon Raid": [{c:55}],
    "Demon Raid > Demon Low Slash": [{c:52}, {hap:4}, {pc:19}],
    "Demon Raid > Demon Guillotine": [],
    "Demon Raid > Demon Blade Kick": [],
    "Demon Raid > Demon Swoop": [],
    "OD Demon Raid": [],
    "OD Demon Raid > Demon Low Slash": [{c:52}, {hap:4}, {pc:19}],
    "OD Demon Raid > Demon Guillotine": [],
    "OD Demon Raid > Demon Blade Kick": [],
    "OD Demon Raid > Demon Swoop": [],
    "OD Demon Raid > OD Demon Gou Zanku": [],
    "OD Demon Raid > OD Hyakki Gorasen": [],
    "Ashura Senku (backward)": [{c:49}],
    "Ashura Senku (forward)": [{c:51}],
    "Ashura Senku (forward) > Oboro Throw": [{c:30}, {hap:3}, {pc:50}],
    "Messatsu Gohado": [{sip:9}, {pat:38}, {pc:59}],
    "Tenma Gozanku": [{c:13}, {pat:30}],
    "Empyrean's End": [{ip:8}, {hap:3}, {pc:52}],
    "Sip of Calamity": [{ip:7}, {hap:4}, {pc:58}],
    "Sip of Calamity (Critical Art)": [{ip:7}, {hap:4}, {pc:58}],
    "Shun Goku Satsu": [{ip:1}, {c:4}, {pip:21}, {pc:57}],
    "Double Zanku Hadoken": [],
    "Kongou Kokuretsuzan (KKZ)": [{ip:7}, {hap:30}, {pc:41}],
    "Misogi": [{ip:4}, {hap:7}, {pc:87}]
  }
}
export default data;