const data = {
  "base": {
    "Stand LP": [{c:4}, {hap:3}, {pc:10}],
    "Stand MP": [{c:9}, {hap:3}, {pc:15}],
    "Stand HP": [{c:9}, {hap:7}, {pc:22}],
    "Stand LK": [{c:3}, {hap:4}, {pc:7}],
    "Stand MK": [{c:7}, {hap:3}, {pc:20}],
    "Stand HK": [{c:6}, {hap:9}, {pc:18}],
    "Crouch LP": [{c:5}, {hap:6}, {pc:8}],
    "Crouch MP": [{c:8}, {hap:5}, {pc:16}],
    "Crouch HP": [{c:14}, {hap:5}, {pc:20}],
    "Crouch LK": [{c:4}, {hap:2}, {pc:10}],
    "Crouch MK": [{c:7}, {hap:3}, {pc:18}],
    "Crouch HK": [{c:10}, {hap:4}, {pc:23}],
    "Jump LP": [{c:3}, {hap:5}],
    "Jump MP": [{c:6}, {hap:7}],
    "Jump HP": [{c:8}, {hap:4}],
    "Jump LK": [{c:4}, {hap:6}],
    "Jump MK": [{c:6}, {hap:6}],
    "Jump HK": [{c:10}, {hap:6}],
    "Neutral Jump HP": [{c:6}, {hap:3}],
    "Rock Crusher": [{c:19}, {hap:3}, {pc:20}],
    "Double Knee Bombs": [{c:8}, {hap:3}, {pc:7}, {hap:2}, {pc:18}],
    "Wild Edge": [{c:8}, {hap:6}, {pc:12}],
    "Wild Nail": [{c:17}, {hap:4}, {pc:31}],
    "Amazon River Run": [{c:13}, {hap:10}, {pc:22}],
    "Coward Crouch": [{c:98}],
    "Wild Lift": [{c:25}, {hap:7}, {pc:31}],
    "Raid Jump": [{c:19}, {hap:3}, {pc:20}],
    "Surprise Forward Hop": [{c:27}],
    "Surprise Back Hop": [{c:33}],
    "Wild Fang": [{c:4}, {hap:3}, {pc:23}],
    "Jungle Flip": [{c:4}, {hap:3}, {pc:23}],
    "Wild Bites": [{c:4}, {hap:3}, {pc:23}],
    "Drive Impact: Wild Scratch": [{pcat:25}, {hap:2}, {pc:35}],
    "Drive Reversal: Quick Rolling Attack": [{ip:19}, {hap:3}, {pc:31}],
    "Drive Parry": [],
    "Drive Rush": [],
    "Taunt": [],
    "Electric Thunder": [{c:9}, {hap:2}, {pc:3}, {hap:2}, {pc:3}, {hap:2}, {pc:17}],
    "OD Electric Thunder": [{c:9}, {hap:2}, {pc:3}, {hap:2}, {pc:3}, {hap:2}, {pc:17}],
    "LP Rolling Attack": [{c:9}, {hap:11}, {pc:11}],
    "MP Rolling Attack": [{c:11}, {hap:19}, {pc:11}],
    "HP Rolling Attack": [{c:21}, {hap:20}, {pc:25}],
    "OD Rolling Attack": [{c:17}, {hap:22}, {pc:17}],
    "LK Vertical Rolling Attack": [{c:7}, {hap:19}, {pc:48}],
    "MK Vertical Rolling Attack": [{c:7}, {hap:19}, {pc:48}],
    "HK Vertical Rolling Attack": [{c:7}, {hap:19}, {pc:48}],
    "OD Vertical Rolling Attack": [{ip:6}, {hap:8}, {pc:2}, {hap:6}, {pc:48}],
    "LK Backstep Rolling Attack": [{c:40}, {hap:24}, {pc:5}],
    "MK Backstep Rolling Attack": [{c:40}, {hap:27}, {pc:5}],
    "HK Backstep Rolling Attack": [{c:40}, {hap:29}, {pc:5}],
    "OD Backstep Rolling Attack": [{c:7}, {hap:5}, {pc:28}, {hap:21}, {pc:1}, {hap:4}, {pc:4}],
    "Aerial Rolling Attack (air)": [{c:12}, {hap:11}],
    "OD Aerial Rolling Attack (air)": [{c:12}, {hap:11}],
    "LK Wild Hunt": [{c:33}, {hap:3}, {pc:57}],
    "MK Wild Hunt": [{c:38}, {hap:3}, {pc:57}],
    "HK Wild Hunt": [{c:42}, {hap:3}, {pc:57}],
    "OD Wild Hunt": [{c:31}, {hap:3}, {pc:57}],
    "Blanka-chan Bomb": [{c:50}],
    "Blanka-chan Bomb (Charge)": [],
    "Blanka-chan Bomb (OD Charge)": [],
    "Blanka-chan Bomb (SA1 Charge)": [],
    "Shout of Earth": [{sip:7}, {pat:9}, {pc:62}],
    "Lightning Beast": [{c:10}],
    "Ground Shave Cannonball": [{ip:9}, {hap:3}, {pc:61}],
    "Ground Shave Cannonball (Critical Art)": [{ip:9}, {hap:3}, {pc:61}]
  },
  "lightning-beast": {
    "Rolling Cannon": [],
    "Electric Thunder": [],
    "OD Electric Thunder": [],
    "LP Rolling Attack": [],
    "MP Rolling Attack": [],
    "HP Rolling Attack": [],
    "OD Rolling Attack": [],
    "LK Vertical Rolling Attack": [],
    "MK Vertical Rolling Attack": [],
    "HK Vertical Rolling Attack": [],
    "OD Vertical Rolling Attack": [],
    "LK Backstep Rolling Attack": [],
    "MK Backstep Rolling Attack": [],
    "HK Backstep Rolling Attack": [],
    "OD Backstep Rolling Attack": [],
    "Aerial Rolling Attack (air)": [],
    "OD Aerial Rolling Attack (air)": [],
    "Shout of Earth": []
  }
}
export default data;