const data = {
  "base": {
    "Stand LP": [{c:3}, {hap:3}, {pc:7}],
    "Stand MP": [{c:4}, {hap:4}, {pc:13}],
    "Stand HP": [{c:7}, {hap:3}, {pc:20}],
    "Stand LK": [{c:4}, {hap:3}, {pc:10}],
    "Stand MK": [{c:7}, {hap:3}, {pc:18}],
    "Stand HK": [{c:3}, {hap:2}, {pc:8}],
    "Crouch LP": [{c:3}, {hap:3}, {pc:7}],
    "Crouch MP": [{c:6}, {hap:3}, {pc:14}],
    "Crouch HP": [{c:9}, {hap:4}, {pc:15}],
    "Crouch LK": [{c:4}, {hap:3}, {pc:7}],
    "Crouch MK": [{c:7}, {hap:3}, {pc:18}],
    "Crouch HK": [{c:8}, {hap:3}, {pc:24}],
    "Jump LP": [{c:3}, {hap:10}],
    "Jump MP": [{c:5}, {hap:8}],
    "Jump HP": [{c:7}, {hap:5}],
    "Jump LK": [{c:3}, {hap:10}],
    "Jump MK": [{c:6}, {hap:6}],
    "Jump HK": [{c:9}, {hap:6}],
    "Lift Uppercut": [{c:4}, {hap:5}, {pc:12}],
    "Assault Blade": [{c:8}, {hap:3}, {pc:18}],
    "Delayed Ripper": [{c:17}, {hap:3}, {pc:25}],
    "Lift Combination": [{c:4}, {hap:1}, {c:8}, {hap:3}, {pc:25}],
    "Swing Combination": [{c:7}, {hap:1}, {c:12}, {hap:4}, {pc:12}, {hap:3}, {pc:29}],
    "Rough Landing": [{c:4}, {hap:3}, {pc:23}],
    "Delta Throw": [{c:4}, {hap:3}, {pc:23}],
    "Leg Scissors Choke": [{c:4}, {hap:3}],
    "Drive Impact: Spin Raider": [{c:25}, {hap:2}, {pcat:35}],
    "Drive Reversal: Countersnipe": [{ip:19}, {hap:3}, {pc:26}],
    "Drive Parry": [{c:45}],
    "Drive Rush": [{c:45}],
    "Taunt": [],
    "LK Spiral Arrow": [{c:8}, {hap:13}, {pc:21}],
    "MK Spiral Arrow": [{c:8}, {hap:15}, {pc:21}],
    "HK Spiral Arrow": [{c:14}, {hap:3}, {pc:1}, {hap:12}, {pc:21}],
    "HK Spiral Arrow (hold)": [{c:26}, {hap:3}, {pc:1}, {hap:12}, {pc:20}],
    "OD Spiral Arrow": [{c:12}, {hap:3}, {pc:1}, {hap:12}, {pc:20}],
    "LK Cannon Spike": [{c:4}, {hap:12}, {pc:40}],
    "MK Cannon Spike": [{c:5}, {hap:12}, {pc:41}],
    "HK Cannon Spike": [{c:6}, {hap:12}, {pc:44}],
    "HK Cannon Spike (hold)": [{c:19}, {ip:4}, {hap:12}, {pc:45}],
    "OD Cannon Spike": [{ip:5}, {hap:12}, {pc:46}],
    "LP Quick Spin Knuckle": [{c:20}, {hap:4}, {pc:16}],
    "MP Quick Spin Knuckle": [{c:8}, {pip:15}, {hap:4}, {pc:16}],
    "HP Quick Spin Knuckle": [{c:8}, {pip:19}, {hap:4}, {pc:17}],
    "OD Quick Spin Knuckle": [{c:8}, {pip:16}, {hap:4}, {pc:17}],
    "Cannon Strike": [{c:12}, {hap:11}],
    "OD Cannon Strike": [{c:12}, {hap:12}],
    "Hooligan Combination": [{c:49}],
    "HP Hooligan Combination (hold)": [{c:69}],
    "OD Hooligan Combination": [{c:49}],
    "Hooligan Combination > Razor Edge Slicer": [{c:49}, {hap:9}, {pc:13}],
    "HP Hooligan Combination (hold) > Razor Edge Slicer": [{c:69}, {hap:9}, {pc:10}, {hap:5}, {pc:17}],
    "OD Hooligan Combination > Razor Edge Slicer": [{c:49}, {hap:9}, {pc:10}, {hap:5}, {pc:17}],
    "Hooligan Combination > Cannon Strike": [{c:32}, {hap:10}, {pc:12}],
    "HP Hooligan Combination (hold) > Cannon Strike": [{c:52}, {hap:6}, {pc:12}],
    "OD Hooligan Combination > Cannon Strike": [{c:32}, {hap:6}, {pc:12}],
    "Hooligan Combination > Reverse Edge": [{c:37}, {hap:4}, {pc:15}],
    "HP Hooligan Combination (hold) > Reverse Edge": [{c:57}, {hap:4}, {pc:14}, {hap:4}, {pc:13}],
    "OD Hooligan Combination > Reverse Edge": [{c:37}, {hap:4}, {pc:14}, {hap:4}, {pc:13}],
    "Hooligan Combination > Fatal Leg Twister": [{c:29}, {hap:3}, {pc:37}],
    "HP Hooligan Combination (hold) > Fatal Leg Twister": [{c:49}, {hap:3}, {pc:32}],
    "OD Hooligan Combination > Fatal Leg Twister": [{c:29}, {hap:3}, {pc:32}],
    "Hooligan Combination > Silent Step": [{c:42}],
    "HP Hooligan Combination (hold) > Silent Step": [{c:57}],
    "OD Hooligan Combination > Silent Step": [{c:37}],
    "Spin Drive Smasher": [{sip:8}, {hap:3}, {pc:1}, {hap:12}, {pc:38}],
    "Killer Bee Spin": [{c:12}, {hap:9}, {pc:37}],
    "Aerial Killer Bee Spin": [{c:12}, {hap:11}, {pc:37}],
    "Delta Red Assault": [{ip:8}, {hap:15}, {pc:38}],
    "Delta Red Assault (Critical Art)": [{ip:8}, {hap:15}, {pc:38}]
  }
}
export default data;