export default function Cammy() {
  return ({
    "base": {
      "Stand LP": [],
      "Stand MP": [],
      "Stand HP": [],
      "Stand LK": [],
      "Stand MK": [],
      "Stand HK": [],
      "Crouch LP": [],
      "Crouch MP": [],
      "Crouch HP": [],
      "Crouch LK": [],
      "Crouch MK": [],
      "Crouch HK": [],
      "Jump LP": [],
      "Jump MP": [],
      "Jump HP": [],
      "Jump LK": [],
      "Jump MK": [],
      "Jump HK": [],
      "Lift Uppercut": [],
      "Assault Blade": [],
      "Delayed Ripper": [],
      "Lift Combination": [],
      "Swing Combination": [],
      "Rough Landing": [],
      "Delta Throw": [],
      "Leg Scissors Choke": [],
      "Drive Impact: Spin Raider": [],
      "Drive Reversal: Countersnipe": [],
      "Drive Parry": [],
      "Drive Rush": [],
      "Taunt": [],
      "LK Spiral Arrow": [],
      "MK Spiral Arrow": [],
      "HK Spiral Arrow": [],
      "HK Spiral Arrow (hold)": [],
      "OD Spiral Arrow": [],
      "LK Cannon Spike": [],
      "MK Cannon Spike": [],
      "HK Cannon Spike": [],
      "HK Cannon Spike (hold)": [],
      "OD Cannon Spike": [],
      "LP Quick Spin Knuckle": [],
      "MP Quick Spin Knuckle": [],
      "HP Quick Spin Knuckle": [],
      "OD Quick Spin Knuckle": [],
      "Cannon Strike": [],
      "OD Cannon Strike": [],
      "Hooligan Combination": [],
      "HP Hooligan Combination (hold)": [],
      "OD Hooligan Combination": [],
      "Hooligan Combination > Razor Edge Slicer": [],
      "HP Hooligan Combination (hold) > Razor Edge Slicer": [],
      "OD Hooligan Combination > Razor Edge Slicer": [],
      "Hooligan Combination > Cannon Strike": [],
      "HP Hooligan Combination (hold) > Cannon Strike": [],
      "OD Hooligan Combination > Cannon Strike": [],
      "Hooligan Combination > Reverse Edge": [],
      "HP Hooligan Combination (hold) > Reverse Edge": [],
      "OD Hooligan Combination > Reverse Edge": [],
      "Hooligan Combination > Fatal Leg Twister": [],
      "HP Hooligan Combination (hold) > Fatal Leg Twister": [],
      "OD Hooligan Combination > Fatal Leg Twister": [],
      "Hooligan Combination > Silent Step": [],
      "HP Hooligan Combination (hold) > Silent Step": [],
      "OD Hooligan Combination > Silent Step": [],
      "Spin Drive Smasher": [],
      "Killer Bee Spin": [],
      "Aerial Killer Bee Spin": [],
      "Delta Red Assault": [],
      "Delta Red Assault (Critical Art)": []
    }
  })
}