export default function ChunLi() {
  return ({
    "base": {
      "Stand LP": [],
      "Stand MP": [],
      "Stand HP": [],
      "Stand LK": [],
      "Stand MK": [],
      "Stand HK": [],
      "Crouch LP": [],
      "Crouch MP": [],
      "Crouch HP": [],
      "Crouch LK": [],
      "Crouch MK": [],
      "Crouch HK": [],
      "Jump LP": [],
      "Jump MP": [],
      "Jump HP": [],
      "Jump LK": [],
      "Jump MK": [],
      "Jump HK": [],
      "Neutral Jump HK": [],
      "Wall Jump": [],
      "Yoso Kick": [],
      "Soaring Eagle Punches": [],
      "Swift Thrust": [],
      "Hakkei": [],
      "Water Lotus Fist": [],
      "Yokusen Kick": [],
      "Falling Crane": [],
      "Serenity Stream": [],
      "Orchid Palm": [],
      "Snake Strike": [],
      "Lotus Fist": [],
      "Forward Strike": [],
      "Senpu Kick": [],
      "Tenku Kick": [],
      "Koshuto": [],
      "Taiji Fan": [],
      "Ryuseiraku": [],
      "Drive Impact: Hosen Kick": [],
      "Drive Reversal: Hoyoku Kick": [],
      "Drive Parry": [],
      "Drive Rush": [],
      "Taunt": [],
      "LP Kikoken": [],
      "MP Kikoken": [],
      "HP Kikoken": [],
      "OD Kikoken": [],
      "LK Hundred Lightning Kicks": [],
      "MK Hundred Lightning Kicks": [],
      "HK Hundred Lightning Kicks": [],
      "OD Hundred Lightning Kicks": [],
      "Lightning Kick Barrage": [],
      "LK Aerial Hundred Lightning Kicks": [],
      "MK Aerial Hundred Lightning Kicks": [],
      "HK Aerial Hundred Lightning Kicks": [],
      "OD Aerial Hundred Lightning Kicks": [],
      "LK Spinning Bird Kick": [],
      "MK Spinning Bird Kick": [],
      "HK Spinning Bird Kick": [],
      "OD Spinning Bird Kick": [],
      "LK Hazanshu": [],
      "MK Hazanshu": [],
      "HK Hazanshu": [],
      "OD Hazanshu": [],
      "LK Tenshokyaku": [],
      "MK Tenshokyaku": [],
      "HK Tenshokyaku": [],
      "OD Tenshokyaku": [],
      "Kikosho": [],
      "Aerial Kikosho": [],
      "Hoyoku-sen": [],
      "Soten Ranka": [],
      "Soten Ranka (Critical Art)": []
    }
  })
}