const data = {
  "base": {
    "Stand LP": [{c:3}, {hap:3}, {pc:7}],
    "Stand MP": [{c:4}, {hap:4}, {pc:10}],
    "Stand HP": [{c:12}, {hap:3}, {pc:20}],
    "Stand LK": [{c:4}, {hap:3}, {pc:10}],
    "Stand MK": [{c:6}, {hap:4}, {pc:16}],
    "Stand HK": [{c:13}, {hap:3}, {pc:18}],
    "Crouch LP": [{c:3}, {hap:3}, {pc:7}],
    "Crouch MP": [{c:5}, {hap:4}, {pc:13}],
    "Crouch HP": [{c:10}, {hap:3}, {pc:5}, {hap:5}, {pc:18}],
    "Crouch LK": [{c:3}, {hap:2}, {pc:10}],
    "Crouch MK": [{c:6}, {hap:3}, {pc:19}],
    "Crouch HK": [{c:8}, {hap:6}, {pc:19}],
    "Jump LP": [{c:3}, {hap:10}],
    "Jump MP": [{c:6}, {hap:4}, {c:6}, {hap:5}],
    "Jump HP": [{c:8}, {hap:6}],
    "Jump LK": [{c:3}, {hap:8}],
    "Jump MK": [{c:5}, {hap:5}],
    "Jump HK": [{c:7}, {hap:5}],
    "Neutral Jump HK": [{c:7}, {hap:7}],
    "Wall Jump": [{ncar:32}, {c:39}, {ncar:3}],
    "Yoso Kick": [{c:2}, {hap:11}],
    "Soaring Eagle Punches": [{c:8}, {hap:6}, {pc:10}, {hap:4}, {pc:17}],
    "Swift Thrust": [{c:6}, {hap:3}, {pc:15}],
    "Hakkei": [{c:7}, {hap:6}, {pc:14}],
    "Water Lotus Fist": [{c:20}, {hap:4}, {pc:14}],
    "Yokusen Kick": [{c:15}, {hap:2}, {pc:23}],
    "Falling Crane": [{c:36}, {hap:2}, {pc:13}],
    "Serenity Stream": [{c:14}],
    "Orchid Palm": [{c:4}, {hap:5}, {pc:16}],
    "Snake Strike": [{c:10}, {hap:7}, {pc:19}],
    "Lotus Fist": [{c:22}, {hap:2}, {pc:6}, {hap:2}, {pc:19}],
    "Forward Strike": [{c:7}, {hap:5}, {pc:13}],
    "Senpu Kick": [{c:9}, {hap:5}, {pc:22}],
    "Tenku Kick": [{c:7}, {hap:5}, {pc:22}],
    "Koshuto": [{c:4}, {hap:3}, {pc:23}],
    "Taiji Fan": [{c:4}, {hap:3}, {pc:23}],
    "Ryuseiraku": [{c:4}, {hap:3}, {pc:3}],
    "Drive Impact: Hosen Kick": [{pcat:25}, {hap:2}, {pc:35}],
    "Drive Reversal: Hoyoku Kick": [{ip:19}, {hap:3}, {pc:10}, {hap:3}, {pc:33}],
    "Drive Parry": [{c:45}],
    "Drive Rush": [{c:45}],
    "Taunt": [],
    "LP Kikoken": [{c:14}, {pat:33}],
    "MP Kikoken": [{c:11}, {pat:34}],
    "HP Kikoken": [{c:10}, {pat:25}, {pc:8}],
    "OD Kikoken": [{c:10}, {pat:29}],
    "LK Hundred Lightning Kicks": [{c:7}, {hap:2}, {pc:5}, {hap:2}, {pc:5}, {hap:2}, {pc:20}],
    "MK Hundred Lightning Kicks": [{c:13}, {hap:2}, {pc:4}, {hap:2}, {pc:4}, {hap:2}, {pc:5}, {hap:2}, {pc:22}],
    "HK Hundred Lightning Kicks": [{c:22}, {hap:2}, {pc:3}, {hap:2}, {pc:2}, {hap:2}, {pc:4}, {hap:2}, {pc:6}, {hap:2}, {pc:15}],
    "OD Hundred Lightning Kicks": [{c:7}, {hap:2}, {pc:4}, {hap:2}, {pc:4}, {hap:2}, {pc:4}, {hap:2}, {pc:4}, {hap:2}, {pc:21}],
    "Lightning Kick Barrage": [{c:7}, {hap:2}, {pc:4}, {hap:2}, {pc:4}, {hap:2}, {pc:4}, {hap:2}, {pc:4}, {hap:2}, {pc:1}, {c:10}, {hap:2}, {pc:5}, {hap:2}, {pc:4}, {hap:2}, {pc:5}, {hap:2}, {pc:13}, {hap:3}, {pc:25}],
    "LK Aerial Hundred Lightning Kicks": [{c:7}, {hap:2}, {pc:4}, {hap:2}, {pc:4}, {hap:2}, {pc:21}],
    "MK Aerial Hundred Lightning Kicks": [{c:9}, {hap:2}, {pc:4}, {hap:2}, {pc:4}, {hap:2}, {pc:5}, {hap:2}, {pc:23}],
    "HK Aerial Hundred Lightning Kicks": [{c:11}, {hap:2}, {pc:4}, {hap:2}, {pc:3}, {hap:2}, {pc:4}, {hap:2}, {pc:3}, {hap:4}, {pc:28}],
    "OD Aerial Hundred Lightning Kicks": [{c:9}, {hap:2}, {pc:4}, {hap:2}, {pc:2}, {hap:2}, {pc:3}, {hap:2}, {pc:2}, {hap:2}, {pc:3}, {hap:2}, {pc:26}],
    "LK Spinning Bird Kick": [{c:8}, {hap:2}, {pc:6}, {hap:2}, {pc:6}, {hap:2}, {pc:30}],
    "MK Spinning Bird Kick": [{c:15}, {hap:2}, {pc:6}, {hap:2}, {pc:6}, {hap:2}, {pc:7}, {hap:2}, {pc:4}, {hap:2}, {pc:29}],
    "HK Spinning Bird Kick": [{c:20}, {hap:2}, {pc:4}, {hap:2}, {pc:8}, {hap:2}, {pc:6}, {hap:2}, {pc:5}, {hap:2}, {pc:5}, {hap:2}, {pc:3}, {hap:2}, {pc:30}],
    "ODs Spinning Bird Kick": [{c:14}, {hap:2}, {pc:4}, {hap:2}, {pc:4}, {hap:2}, {pc:5}, {hap:2}, {pc:4}, {hap:2}, {pc:5}, {hap:2}, {pc:4}, {hap:2}, {pc:23}],
    "LK Hazanshu": [{c:6}, {pip:12}, {c:4}, {hap:2}, {pc:21}],
    "MK Hazanshu": [{c:6}, {pip:15}, {c:5}, {hap:3}, {pc:16}],
    "HK Hazanshu": [{c:6}, {pip:20}, {c:5}, {hap:3}, {pc:18}],
    "OD Hazanshu": [{c:6}, {pip:19}, {hap:3}, {pc:16}],
    "LK Tenshokyaku": [{c:4}, {hap:2}, {pc:10}, {hap:2}, {pc:39}],
    "MK Tenshokyaku": [{c:6}, {hap:2}, {pc:10}, {hap:2}, {pc:43}],
    "HK Tenshokyaku": [{c:8}, {hap:2}, {pc:8}, {hap:2}, {pc:8}, {hap:2}, {pc:11}, {hap:2}, {pc:38}],
    "OD Tenshokyaku": [{ip:5}, {hap:3}, {pc:5}, {hap:3}, {pc:41}],
    "Kikosho": [{sip:6}, {pat:70}, {pc:46}],
    "Aerial Kikosho": [{c:6}, {pat:50}, {pc:42}],
    "Hoyoku-sen": [{ip:10}, {hap:2}, {pc:1}, {hap:2}, {pc:1}, {hap:2}, {pc:1}, {hap:2}, {pc:2}, {hap:2}, {pc:1}, {hap:2}, {pc:1}, {hap:2}, {pc:1}, {hap:2}, {pc:11}, {hap:2}, {pc:2}, {hap:2}, {pc:2}, {hap:2}, {pc:2}, {hap:2}, {pc:2}, {hap:2}, {pc:2}, {hap:2}, {pc:1}, {hap:2}, {pc:23}, {hap:3}, {pc:48}],
    "Soten Ranka": [{ip:7}, {hap:2}, {pc:24}, {hap:1}, {pc:7}, {hap:40}],
    "Soten Ranka (Critical Art)": [{ip:7}, {hap:2}, {pc:24}, {hap:1}, {pc:7}, {hap:40}]
  }
}
export default data;