export default function DeeJay() {
  return ({
    "base": {
      "Stand LP": [],
      "Stand MP": [],
      "Stand HP": [],
      "Stand LK": [],
      "Stand MK": [],
      "Stand HK": [],
      "Crouch LP": [],
      "Crouch MP": [],
      "Crouch HP": [],
      "Crouch LK": [],
      "Crouch MK": [],
      "Crouch HK": [],
      "Jump LP": [],
      "Jump MP": [],
      "Jump HP": [],
      "Jump LK": [],
      "Jump MK": [],
      "Jump HK": [],
      "Knee Shot": [],
      "Party in the Air": [],
      "Sunrise Heel": [],
      "Face Breaker": [],
      "Threebeat Combo 1": [],
      "Threebeat Combo 2": [],
      "Funky Dance 1": [],
      "Funky Dance 2": [],
      "Funky Dance Feint": [],
      "Dee Jay Special 1": [],
      "Dee Jay Special 2": [],
      "Speedy Maracas": [],
      "Diss Track": [],
      "Flip Throw": [],
      "Drive Impact: Wild Beat": [],
      "Drive Reversal: Leg Scratch": [],
      "Drive Parry": [],
      "Drive Rush": [],
      "Taunt": [],
      "LP Air Slasher": [],
      "MP Air Slasher": [],
      "HP Air Slasher": [],
      "OD Air Slasher": [],
      "LK Jackknife Maximum": [],
      "MK Jackknife Maximum": [],
      "HK Jackknife Maximum": [],
      "OD Jackknife Maximum": [],
      "LK Double Rolling Sobat": [],
      "MK Double Rolling Sobat": [],
      "HK Double Rolling Sobat": [],
      "OD Double Rolling Sobat": [],
      "LP Machine Gun Upper": [],
      "MP Machine Gun Upper": [],
      "HP Machine Gun Upper": [],
      "OD Machine Gun Upper": [],
      "Jus Cool": [],
      "Jus Cool > Funky Slicer": [],
      "Jus Cool > Waning Moon": [],
      "Jus Cool > Maximum Strike": [],
      "Jus Cool > Juggling Dash": [],
      "Jus Cool > Juggling Dash > Juggling Sway": [],
      "OD Jus Cool": [],
      "OD Jus Cool > Funky Slicer": [],
      "OD Jus Cool > Waning Moon": [],
      "OD Jus Cool > Maximum Strike": [],
      "OD Jus Cool > Juggling Dash": [],
      "OD Jus Cool > Juggling Dash > Juggling Sway": [],
      "The Greatest Sobat": [],
      "Lowkey Sunrise Festival": [],
      "Marvelous Sunrise Festival": [],
      "Headliner Sunrise Festival": [],
      "Climactic Strike": [],
      "Encore Beat": [],
      "Weekend Pleasure": [],
      "Weekend Pleasure (Critical Art)": []
    }
  })
}