const data = {
  "base": {
    "Stand LP": [{c:3}, {hap:3}, {pc:6}],
    "Stand MP": [{c:6}, {hap:3}, {pc:13}],
    "Stand HP": [{c:8}, {hap:6}, {pc:18}],
    "Stand LK": [{c:4}, {hap:2}, {pc:12}],
    "Stand MK": [{c:8}, {hap:3}, {pc:16}],
    "Stand HK": [{c:11}, {hap:3}, {pc:26}],
    "Crouch LP": [{c:4}, {hap:3}, {pc:8}],
    "Crouch MP": [{c:5}, {hap:4}, {pc:14}],
    "Crouch HP": [{c:7}, {hap:2}, {pc:20}],
    "Crouch LK": [{c:4}, {hap:2}, {pc:10}],
    "Crouch MK": [{c:7}, {hap:4}, {pc:19}],
    "Crouch HK": [{c:13}, {hap:10}, {pc:15}],
    "Jump LP": [{c:3}, {hap:7}],
    "Jump MP": [{c:5}, {hap:4}],
    "Jump HP": [{c:8}, {hap:6}],
    "Jump LK": [{c:3}, {hap:6}],
    "Jump MK": [{c:7}, {hap:6}],
    "Jump HK": [{c:9}, {hap:5}],
    "Knee Shot": [{c:5}, {hap:23}, {pc:3}],
    "Party in the Air": [{c:5}, {hap:1}, {c:7}, {hap:7}],
    "Sunrise Heel": [{c:18}, {hap:5}, {pc:16}],
    "Face Breaker": [{c:6}, {hap:6}, {pc:20}],
    "Threebeat Combo 1": [{c:3}, {hap:1}, {c:8}, {hap:3}, {pc:18}],
    "Threebeat Combo 2": [{c:3}, {hap:1}, {c:8}, {hap:1}, {pc:13}, {hap:3}, {pc:21}],
    "Funky Dance 1": [{c:6}, {hap:3}, {pc:1}, {c:11}, {hap:2}, {pc:17}],
    "Funky Dance 2": [{c:6}, {hap:3}, {pc:1}, {c:11}, {hap:2}, {c:19}, {hap:2}, {pc:24}],
    "Funky Dance Feint": [{c:6}, {hap:3}, {pc:1}, {c:11}, {hap:2}, {c:23}],
    "Dee Jay Special 1": [{c:6}, {hap:3}, {pc:1}, {c:10}, {hap:7}, {pc:24}],
    "Dee Jay Special 2": [{c:6}, {hap:3}, {pc:1}, {c:10}, {hap:4}, {c:12}, {hap:3}, {pc:30}],
    "Speedy Maracas": [{c:132}],
    "Diss Track": [{c:4}, {hap:3}, {pc:23}],
    "Flip Throw": [{c:4}, {hap:3}, {pc:23}],
    "Drive Impact: Wild Beat": [{pcat:25}, {hap:2}, {pc:35}],
    "Drive Reversal: Leg Scratch": [{ip:19}, {hap:3}, {pc:26}],
    "Drive Parry": [{c:45}],
    "Drive Rush": [{c:45}],
    "Taunt": [],
    "LP Air Slasher": [{c:21}],
    "MP Air Slasher": [{c:16}, {pat:28}],
    "HP Air Slasher": [{c:16}, {pat:44}],
    "OD Air Slasher": [{c:9}, {pat:11}, {pc:1}, {pat:24}],
    "LK Jackknife Maximum": [{c:51}],
    "MK Jackknife Maximum": [{c:5}, {hap:3}, {pc:10}, {hap:4}, {pc:32}],
    "HK Jackknife Maximum": [{c:5}, {hap:4}, {pc:8}, {hap:5}, {pc:8}, {hap:4}, {pc:32}],
    "OD Jackknife Maximum": [{ip:5}, {hap:5}, {pc:7}, {hap:3}, {pc:9}, {hap:3}, {pc:44}],
    "LK Double Rolling Sobat": [{c:26}],
    "MK Double Rolling Sobat": [{c:11}, {hap:3}, {pc:23}],
    "HK Double Rolling Sobat": [{c:14}, {hap:3}, {pc:18}, {hap:4}, {pc:24}],
    "OD Double Rolling Sobat": [{c:18}, {hap:2}, {pc:9}, {hap:3}, {pc:19}],
    "LP Machine Gun Upper": [{c:14}, {hap:4}, {pc:35}],
    "MP Machine Gun Upper": [{c:21}, {hap:4}, {pc:35}],
    "HP Machine Gun Upper": [{c:27}, {hap:4}, {pc:35}],
    "OD Machine Gun Upper": [{c:27}, {hap:4}, {pc:35}],
    "Jus Cool": [{c:37}],
    "Jus Cool > Funky Slicer": [{c:24}, {hap:3}, {pc:25}],
    "Jus Cool > Waning Moon": [{c:37}, {hap:3}, {pc:16}],
    "Jus Cool > Maximum Strike": [{c:27}, {hap:5}, {pc:25}],
    "Jus Cool > Juggling Dash": [{c:13}, {pip:20}, {c:7}],
    "Jus Cool > Juggling Dash > Juggling Sway": [{c:13}, {pip:17}, {c:29}],
    "OD Jus Cool": [{c:7}, {hap:5}, {pc:36}],
    "OD Jus Cool > Funky Slicer": [{c:7}, {hap:5}, {pc:21}, {hap:3}, {pc:24}],
    "OD Jus Cool > Waning Moon": [{c:7}, {hap:5}, {pc:31}, {hap:5}, {pc:17}],
    "OD Jus Cool > Maximum Strike": [{c:7}, {hap:5}, {pc:23}, {hap:5}, {pc:21}],
    "OD Jus Cool > Juggling Dash": [{c:7}, {hap:5}, {pc:7}, {pip:17}, {pc:5}],
    "OD Jus Cool > Juggling Dash > Juggling Sway": [{c:7}, {hap:5}, {pc:7}, {pip:16}, {pc:22}],
    "The Greatest Sobat": [{c:6}, {hap:4}, {pc:33}],
    "Lowkey Sunrise Festival": [{ip:11}, {hap:5}, {pc:46}],
    "Marvelous Sunrise Festival": [{ip:11}, {hap:5}, {pc:46}],
    "Headliner Sunrise Festival": [{ip:11}, {hap:5}, {pc:46}],
    "Climactic Strike": [],
    "Encore Beat": [],
    "Weekend Pleasure": [{ip:8}, {hap:5}, {pc:48}],
    "Weekend Pleasure (Critical Art)": [{ip:8}, {hap:5}, {pc:48}]
  }
}

export default data;