export default function Dhalsim() {
  return ({
    "base": {
      "Stand LP": [],
      "Stand MP": [],
      "Stand HP": [],
      "Stand LK": [],
      "Stand MK": [],
      "Stand HK": [],
      "Crouch LP": [],
      "Crouch MP": [],
      "Crouch HP": [],
      "Crouch LK": [],
      "Crouch MK": [],
      "Crouch HK": [],
      "Jump LP": [],
      "Jump MP": [],
      "Jump HP": [],
      "Jump LK": [],
      "Jump MK": [],
      "Jump HK": [],
      "LK Drill Kick": [],
      "MK Drill Kick": [],
      "HK Drill Kick": [],
      "Yoga Mummy": [],
      "Yoga Uppercut": [],
      "Yoga Lance": [],
      "Nirvana Punch": [],
      "Agile Kick": [],
      "Divine Kick": [],
      "Thrust Kick": [],
      "Yoga Mountain": [],
      "Karma Kick": [],
      "Yoga Smash": [],
      "Yoga Throw": [],
      "Yoga Splash": [],
      "Drive Impact: Yoga Rise": [],
      "Drive Reversal: Yoga Illusion": [],
      "Drive Parry": [],
      "Drive Rush": [],
      "Taunt": [],
      "Yoga Float": [],
      "Aerial Yoga Float (air)": [],
      "Yoga Teleport": [],
      "Aerial Yoga Teleport (air)": [],
      "Yoga Fire": [],
      "Yoga Fire (hold)": [],
      "OD Yoga Fire": [],
      "Yoga Arch": [],
      "OD Yoga Arch": [],
      "LP Yoga Flame": [],
      "MP Yoga Flame": [],
      "HP Yoga Flame": [],
      "OD Yoga Flame": [],
      "LK Yoga Blast": [],
      "MK Yoga Blast": [],
      "HK Yoga Blast": [],
      "OD Yoga Blast": [],
      "Yoga Comet (air)": [],
      "OD Yoga Comet (air)": [],
      "Yoga Inferno": [],
      "Yoga Sunburst": [],
      "Yoga Sunburst (hold)": [],
      "Merciless Yoga": [],
      "Merciless Yoga (Critical Art)": []
    }
  })
}