const data = {
  "base": {
    "Stand LP": [{c:3}, {hap:3}, {pc:8}],
    "Stand MP": [{c:13}, {hap:3}, {pc:19}],
    "Stand HP": [{c:15}, {hap:4}, {pc:27}],
    "Stand LK": [{c:8}, {hap:4}, {pc:11}],
    "Stand MK": [{c:11}, {hap:3}, {pc:18}],
    "Stand HK": [{c:16}, {hap:3}, {pc:20}],
    "Crouch LP": [{c:4}, {hap:3}, {pc:9}],
    "Crouch MP": [{c:11}, {hap:3}, {pc:16}],
    "Crouch HP": [{c:18}, {hap:4}, {pc:24}],
    "Crouch LK": [{c:3}, {hap:7}, {pc:16}],
    "Crouch MK": [{c:9}, {hap:12}, {pc:14}],
    "Crouch HK": [{c:11}, {hap:16}, {pc:20}],
    "Jump LP": [{c:3}, {hap:3}],
    "Jump MP": [{c:8}, {hap:6}],
    "Jump HP": [{c:12}, {hap:4}],
    "Jump LK": [{c:5}, {hap:4}],
    "Jump MK": [{c:10}, {hap:6}],
    "Jump HK": [{c:9}, {hap:10}],
    "LK Drill Kick": [{c:8}, {hap:16}, {pc:11}],
    "MK Drill Kick": [{c:8}, {hap:12}, {pc:11}],
    "HK Drill Kick": [{c:8}, {hap:10}, {pc:11}],
    "Yoga Mummy": [{c:9}, {hap:17}, {pc:9}],
    "Yoga Uppercut": [{c:6}, {hap:6}, {pc:16}],
    "Yoga Lance": [{c:13}, {hap:7}, {pc:29}],
    "Nirvana Punch": [{c:9}, {hap:4}, {pc:20}],
    "Agile Kick": [{c:4}, {hap:3}, {pc:10}],
    "Divine Kick": [{c:6}, {hap:4}, {pc:17}],
    "Thrust Kick": [{c:7}, {hap:3}, {pc:20}],
    "Yoga Mountain": [{c:13}, {hap:6}, {pc:20}],
    "Karma Kick": [{c:8}, {hap:3}, {pc:22}],
    "Yoga Smash": [{c:4}, {hap:3}, {pc:23}],
    "Yoga Throw": [{c:4}, {hap:3}, {pc:23}],
    "Yoga Splash": [{c:4}, {hap:3}, {pc:23}],
    "Drive Impact: Yoga Rise": [{pcat:25}, {hap:2}, {pc:35}],
    "Drive Reversal: Yoga Illusion": [{ip:19}, {hap:3}, {pc:6}, {hap:3}, {pc:26}],
    "Drive Parry": [{c:45}],
    "Drive Rush": [{c:45}],
    "Taunt": [],
    "Yoga Float": [{c:36}],
    "Aerial Yoga Float (air)": [{c:15}],
    "Yoga Teleport": [{c:4}, {ip:11}, {pc:31}],
    "Aerial Yoga Teleport (air)": [{c:9}, {ip:6}, {pc:33}],
    "Yoga Fire": [{c:14}, {pat:34}],
    "Yoga Fire (hold)": [{c:42}, {pat:31}],
    "OD Yoga Fire": [{c:12}, {pat:33}],
    "Yoga Arch": [{c:17}, {pat:28}],
    "OD Yoga Arch": [{c:17}, {pat:28}],
    "LP Yoga Flame": [{c:15}, {pat:15}, {pc:15}],
    "MP Yoga Flame": [{c:19}, {pat:15}, {pc:17}],
    "HP Yoga Flame": [{c:25}, {pat:15}, {pc:16}],
    "OD Yoga Flame": [{c:17}, {pat:25}, {pc:24}],
    "LK Yoga Blast": [{c:11}, {pat:10}, {pc:23}],
    "MK Yoga Blast": [{c:14}, {pat:10}, {pc:20}],
    "HK Yoga Blast": [{c:14}, {pat:10}, {pc:20}],
    "OD Yoga Blast": [{c:11}, {pat:10}, {pc:20}],
    "Yoga Comet (air)": [{c:32}, {pat:37}],
    "OD Yoga Comet (air)": [{c:32}, {pat:32}],
    "Yoga Inferno": [{c:9}, {pat:104}, {pc:20}],
    "Yoga Sunburst": [{ip:6}, {pat:61}],
    "Yoga Sunburst (hold)": [{ip:6}, {pat:142}],
    "Merciless Yoga": [{ip:6}, {hap:5}, {pc:75}],
    "Merciless Yoga (Critical Art)": [{ip:6}, {hap:5}, {pc:75}]
  }
}
export default data;