export default function Ed() {
  return ({
    "base": {
      "Stand LP": [],
      "Stand MP": [],
      "Stand HP": [],
      "Stand LK": [],
      "Stand MK": [],
      "Stand HK": [],
      "Crouch LP": [],
      "Crouch MP": [],
      "Crouch HP": [],
      "Crouch LK": [],
      "Crouch MK": [],
      "Crouch HK": [],
      "Jump LP": [],
      "Jump MP": [],
      "Jump HP": [],
      "Jump LK": [],
      "Jump MK": [],
      "Jump HK": [],
      "Psycho Knuckle (level 1)": [],
      "Psycho Knuckle (level 2)": [],
      "Cobra Punch": [],
      "Flicker Combination 1": [],
      "Flicker Combination 2": [],
      "Body Blow Combination": [],
      "Hitman Combination 1": [],
      "Hitman Combination 2": [],
      "Low Smash Combination": [],
      "Face Buster": [],
      "Rib Crusher": [],
      "Drive Impact: Turn Punch": [],
      "Drive Reversal: Hammer Blow": [],
      "Drive Parry": [],
      "Drive Rush": [],
      "Taunt": [],
      "Psycho Spark": [],
      "OD Psycho Spark": [],
      "Psycho Shoot": [],
      "OD Psycho Shoot": [],
      "LP Psycho Uppercut": [],
      "MP Psycho Uppercut": [],
      "HP Psycho Uppercut": [],
      "OD Psycho Uppercut": [],
      "LP Psycho Blitz": [],
      "MP Psycho Blitz": [],
      "HP Psycho Blitz": [],
      "OD Psycho Blitz": [],
      "LK Psycho Flicker": [],
      "LK Psycho Flicker (hold)": [],
      "MK Psycho Flicker": [],
      "MK Psycho Flicker (hold)": [],
      "HK Psycho Flicker": [],
      "HK Psycho Flicker (hold)": [],
      "OD Psycho Flicker": [],
      "Kill Rush (Forward)": [],
      "Kill Rush > Kill Switch Break": [],
      "Kill Rush > Kill Switch Chaser": [],
      "Kill Rush (Backward)": [],
      "Psycho Storm": [],
      "Psycho Cannon": [],
      "Psycho Chamber": [],
      "Critical Art": []
    }
  })
}