const data = {
  "base": {
    "Stand LP": [{c:3}, {hap:3}, {pc:7}],
    "Stand MP": [{c:6}, {hap:3}, {pc:15}],
    "Stand HP": [{c:9}, {hap:4}, {pc:18}],
    "Stand LK": [{c:5}, {hap:2}, {pc:13}],
    "Stand MK": [{c:9}, {hap:2}, {pc:18}],
    "Stand HK": [{c:9}, {hap:3}, {pc:12}],
    "Crouch LP": [{c:3}, {hap:3}, {pc:10}],
    "Crouch MP": [{c:7}, {hap:3}, {pc:19}],
    "Crouch HP": [{c:9}, {hap:4}, {pc:24}],
    "Crouch LK": [{c:4}, {hap:2}, {pc:11}],
    "Crouch MK": [{c:8}, {hap:2}, {pc:16}],
    "Crouch HK": [{c:11}, {hap:2}, {pc:17}],
    "Jump LP": [{c:4}, {hap:5}],
    "Jump MP": [{c:7}, {hap:6}],
    "Jump HP": [{c:8}, {hap:4}],
    "Jump LK": [{c:7}, {hap:3}],
    "Jump MK": [{c:9}, {hap:2}],
    "Jump HK": [{c:7}, {hap:2}],
    "Psycho Knuckle (level 1)": [{c:39}, {hap:15}, {pc:15}],
    "Psycho Knuckle (level 2)": [{c:68}, {hap:15}, {pc:29}],
    "Cobra Punch": [{c:16}, {hap:3}, {pc:21}],
    "Flicker Combination 1": [{c:3}, {hap:3}, {pc:6}, {hap:3}, {pc:7}],
    "Flicker Combination 2": [{c:3}, {hap:3}, {pc:6}, {hap:3}, {pc:6}, {hap:3}, {pc:7}],
    "Body Blow Combination": [{c:6}, {hap:3}, {c:12}, {hap:2}, {pc:23}],
    "Hitman Combination 1": [{c:9}, {hap:2}, {pc:3}, {c:6}, {hap:2}, {pc:20}],
    "Hitman Combination 2": [{c:9}, {hap:2}, {pc:3}, {c:6}, {hap:2}, {pc:3}, {c:10}, {hap:5}, {pc:23}],
    "Low Smash Combination": [{c:11}, {hap:1}, {c:11}, {hap:5}, {pc:19}],
    "Face Buster": [{c:4}, {hap:3}, {pc:23}],
    "Rib Crusher": [{c:4}, {hap:3}, {pc:23}],
    "Drive Impact: Turn Punch": [{pcat:25}, {hap:2}, {pc:35}],
    "Drive Reversal: Hammer Blow": [{ip:19}, {hap:3}, {pc:26}],
    "Drive Parry": [{c:45}],
    "Drive Rush": [{c:45}],
    "Taunt": [],
    "Psycho Spark": [{c:13}, {pat:12}, {pc:8}],
    "OD Psycho Spark": [{c:13}, {pat:12}, {pc:7}],
    "Psycho Shoot": [{c:13}, {pat:8}, {pc:11}, {pat:31}],
    "OD Psycho Shoot": [{c:13}, {pat:5}, {pc:11}, {pat:29}],
    "LP Psycho Uppercut": [{c:8}, {hap:8}, {pc:28}],
    "MP Psycho Uppercut": [{c:13}, {hap:6}, {pc:32}],
    "HP Psycho Uppercut": [{c:15}, {hap:6}, {pc:33}],
    "OD Psycho Uppercut": [{ip:12}, {hap:6}, {pc:36}],
    "LP Psycho Blitz": [{c:10}, {hap:3}, {pc:3}, {hap:3}, {pc:6}, {hap:4}, {pc:14}],
    "MP Psycho Blitz": [{c:12}, {hap:2}, {pc:7}, {hap:3}, {pc:9}, {hap:3}, {pc:16}],
    "HP Psycho Blitz": [{c:14}, {hap:2}, {pc:11}, {hap:2}, {pc:6}, {hap:2}, {pc:23}],
    "OD Psycho Blitz": [{c:12}, {hap:1}, {pc:4}, {hap:1}, {pc:3}, {hap:1}, {pc:3}, {hap:1}, {pc:3}, {hap:1}, {pc:3}, {hap:1}, {pc:8}, {hap:2}, {pc:20}],
    "LK Psycho Flicker": [{c:15}, {pat:4}, {pc:26}],
    "LK Psycho Flicker (hold)": [{c:30}, {pat:5}, {pc:24}],
    "MK Psycho Flicker": [{c:19}, {pat:4}, {pc:26}],
    "MK Psycho Flicker (hold)": [{c:34}, {pat:4}, {pc:24}],
    "HK Psycho Flicker": [{c:16}, {pat:8}, {pc:18}],
    "HK Psycho Flicker (hold)": [{c:30}, {pat:10}, {pc:19}],
    "OD Psycho Flicker": [{c:24}, {pat:4}, {pc:32}],
    "Kill Rush (Forward)": [{c:31}],
    "Kill Rush > Kill Switch Break": [{c:21}, {hap:3}, {pc:20}],
    "Kill Rush > Kill Switch Chaser": [{c:23}, {hap:3}, {pc:20}],
    "Kill Rush (Backward)": [{c:31}],
    "Psycho Storm": [{sip:12}, {hap:2}, {pc:7}, {hap:2}, {pc:16}, {hap:2}, {pc:3}, {hap:2}, {pc:16}, {hap:1}, {pc:1}, {hap:1}, {pc:56}],
    "Psycho Cannon": [{c:7}, {pat:28}],
    "Psycho Chamber": [{ip:9}, {hap:10}, {pc:64}],
    "Critical Art": [{ip:9}, {hap:10}, {pc:64}]
    }
}

export default data;