const data = {
  "base": {
    "Stand LP": [{c:4}, {hap:3}, {pc:10}],
    "Stand MP": [{c:9}, {hap:4}, {pc:13}],
    "Stand HP": [{c:7}, {hap:7}, {pc:20}],
    "Stand LK": [{c:3}, {hap:2}, {pc:9}],
    "Stand MK": [{c:9}, {hap:4}, {pc:16}],
    "Stand HK": [{c:7}, {hap:2}, {pc:1}, {hap:4}, {pc:22}],
    "Crouch LP": [{c:3}, {hap:3}, {pc:10}],
    "Crouch MP": [{c:7}, {hap:4}, {pc:16}],
    "Crouch HP": [{c:10}, {hap:4}, {pc:19}],
    "Crouch LK": [{c:4}, {hap:2}, {pc:9}],
    "Crouch MK": [{c:8}, {hap:3}, {pc:17}],
    "Crouch HK": [{c:10}, {hap:3}, {pc:6}, {hap:5}, {pc:14}],
    "Jump LP": [{c:4}, {hap:6}],
    "Jump MP": [{c:5}, {hap:8}],
    "Jump HP": [{c:8}, {hap:4}],
    "Neutral Jump HP": [{c:9}, {hap:8}],
    "Jump LK": [{c:8}, {hap:6}],
    "Jump MK": [{c:8}, {hap:6}],
    "Jump HK": [{c:9}, {hap:8}],
    "Flying Sumo Press": [{c:10}, {hap:9}],
    "Harai Kick": [{c:13}, {hap:3}, {pc:21}],
    "Power Stomp": [{c:21}, {hap:6}, {pc:18}],
    "Double Slaps": [{c:4}, {hap:3}, {pc:4}, {c:3}, {hap:4}, {pc:20}],
    "Tokoshizume": [{c:9}, {hap:3}, {c:21}, {hap:6}, {pc:18}],
    "Saba Ori": [{c:4}, {hap:3}, {pc:23}],
    "Tawara Throw": [{c:4}, {hap:3}, {pc:23}],
    "Drive Impact: Sumo Crunch": [{pcat:25}, {hap:2}, {pc:35}],
    "Drive Reversal: Raiden-ho": [{ip:19}, {hap:3}, {pc:26}],
    "Drive Parry": [{c:45}],
    "Drive Rush": [{c:45}],
    "Taunt": [],
    "Sumo Spirit": [{c:52}],
    "Neko Damashi": [{c:10}, {hap:5}, {pc:14}],
    "LP Hundred Hand Slap": [{c:11}, {hap:2}, {pc:4}, {hap:2}, {pc:2}, {hap:1}, {pc:2}, {hap:2}, {pc:1}, {hap:1}, {pc:1}, {hap:2}, {pc:14}],
    "MP Hundred Hand Slap": [{c:17}, {hap:2}, {pc:4}, {hap:2}, {pc:1}, {hap:1}, {pc:3}, {hap:1}, {pc:2}, {hap:1}, {pc:3}, {hap:1}, {pc:3}, {hap:1}, {pc:2}, {hap:1}, {pc:2}, {hap:2}, {pc:17}],
    "HP Hundred Hand Slap": [{c:20}, {hap:2}, {pc:4}, {hap:2}, {pc:3}, {hap:1}, {pc:3}, {hap:1}, {pc:3}, {hap:1}, {pc:3}, {hap:1}, {pc:3}, {hap:1}, {pc:3}, {hap:1}, {pc:2}, {hap:1}, {pc:2}, {hap:1}, {pc:2}, {hap:1}, {pc:1}, {hap:2}, {pc:17}],
    "OD Hundred Hand Slap": [{c:18}, {hap:4}, {pc:6}, {hap:2}, {pc:3}, {hap:2}, {pc:3}, {hap:2}, {pc:4}, {hap:2}, {pc:2}, {hap:2}, {pc:2}, {hap:2}, {pc:1}, {hap:2}, {pc:12}],
    "LP Sumo Headbutt": [{c:9}, {hap:22}, {pc:20}],
    "MP Sumo Headbutt": [{c:9}, {hap:24}, {pc:20}],
    "HP Sumo Headbutt": [{c:13}, {hap:28}, {pc:20}],
    "OD Sumo Headbutt": [{pcat:8}, {hap:26}, {pc:30}],
    "LK Sumo Smash": [{c:10}, {hap:4}, {pc:24}, {hap:8}, {pc:17}],
    "MK Sumo Smash": [{c:10}, {hap:4}, {pc:24}, {hap:7}, {pc:17}],
    "HK Sumo Smash": [{c:10}, {hap:4}, {pc:24}, {hap:6}, {pc:17}],
    "OD Sumo Smash": [{c:5}, {hap:12}, {pc:13}, {hap:9}, {pc:17}],
    "LK Oicho Throw": [{c:6}, {hap:3}, {pc:52}],
    "MK Oicho Throw": [{c:6}, {hap:3}, {pc:52}],
    "HK Oicho Throw": [{c:6}, {hap:3}, {pc:52}],
    "OD Oicho Throw": [{c:6}, {hap:3}, {pc:52}],
    "Sumo Dash": [{c:51}],
    "Teppo Double Slap": [{c:22}, {hap:3}, {pc:13}, {hap:3}, {pc:22}],
    "Teppo Triple Slap": [{c:22}, {hap:3}, {pc:13}, {hap:3}, {pc:20}, {hap:3}, {pc:38}],
    "Taiho Cannon Lift": [{c:25}, {hap:3}, {pc:17}, {hap:3}, {pc:15}],
    "OD Sumo Dash": [{c:34}],
    "OD Teppo Double Slap": [{c:22}, {hap:3}, {pc:13}, {hap:3}, {pc:17}],
    "OD Teppo Triple Slap": [{c:22}, {hap:3}, {pc:13}, {hap:3}, {pc:19}, {hap:3}, {pc:38}],
    "OD Taiho Cannon Lift": [{c:22}, {hap:3}, {pc:17}, {hap:3}, {pc:15}],
    "Show of Force": [{sip:6}, {hap:5}, {pc:48}],
    "Ultimate Killer Head Ram": [{ip:1}, {hap:2}, {ip:2}, {hap:18}, {pc:45}],
    "The Final Bout": [{ip:8}, {hap:3}, {pc:8}, {hap:3}, {pc:51}],
    "The Final Bout (Critical Art)": [{ip:8}, {hap:3}, {pc:8}, {hap:3}, {pc:51}]
  }
}
export default data;