export default function EHonda() {
  return ({
    "base": {
      "Stand LP": [],
      "Stand MP": [],
      "Stand HP": [],
      "Stand LK": [],
      "Stand MK": [],
      "Stand HK": [],
      "Crouch LP": [],
      "Crouch MP": [],
      "Crouch HP": [],
      "Crouch LK": [],
      "Crouch MK": [],
      "Crouch HK": [],
      "Jump LP": [],
      "Jump MP": [],
      "Jump HP": [],
      "Neutral Jump HP": [],
      "Jump LK": [],
      "Jump MK": [],
      "Jump HK": [],
      "Flying Sumo Press": [],
      "Harai Kick": [],
      "Power Stomp": [],
      "Double Slaps": [],
      "Tokoshizume": [],
      "Saba Ori": [],
      "Tawara Throw": [],
      "Drive Impact: Sumo Crunch": [],
      "Drive Reversal: Raiden-ho": [],
      "Drive Parry": [],
      "Drive Rush": [],
      "Taunt": [],
      "Sumo Spirit": [],
      "Neko Damashi": [],
      "LP Hundred Hand Slap": [],
      "MP Hundred Hand Slap": [],
      "HP Hundred Hand Slap": [],
      "OD Hundred Hand Slap": [],
      "LP Sumo Headbutt": [],
      "MP Sumo Headbutt": [],
      "HP Sumo Headbutt": [],
      "OD Sumo Headbutt": [],
      "LK Sumo Smash": [],
      "MK Sumo Smash": [],
      "HK Sumo Smash": [],
      "OD Sumo Smash": [],
      "LK Oicho Throw": [],
      "MK Oicho Throw": [],
      "HK Oicho Throw": [],
      "OD Oicho Throw": [],
      "Sumo Dash": [],
      "Teppo Double Slap": [],
      "Teppo Triple Slap": [],
      "Taiho Cannon Lift": [],
      "OD Sumo Dash": [],
      "OD Teppo Double Slap": [],
      "OD Teppo Triple Slap": [],
      "OD Taiho Cannon Lift": [],
      "Show of Force": [],
      "Ultimate Killer Head Ram": [],
      "The Final Bout": [],
      "The Final Bout (Critical Art)": []
    }
  })
}