export default function Guile() {
  return ({
    "base": {
      "Stand LP": [],
      "Stand MP": [],
      "Stand HP": [],
      "Stand LK": [],
      "Stand MK": [],
      "Stand HK": [],
      "Crouch LP": [],
      "Crouch MP": [],
      "Crouch HP": [],
      "Crouch LK": [],
      "Crouch MK": [],
      "Crouch HK": [],
      "Jump LP": [],
      "Jump MP": [],
      "Jump HP": [],
      "Jump LK": [],
      "Jump MK": [],
      "Jump HK": [],
      "Full Bullet Magnum": [],
      "Spinning Back Knuckle": [],
      "Burning Straight": [],
      "Knee Bazooka": [],
      "Rolling Sobat": [],
      "Reverse Spin Kick": [],
      "Guile High Kick": [],
      "Recoil Cannon": [],
      "Double Shot": [],
      "Drake Fang": [],
      "Phantom Cutter": [],
      "Dragon Suplex": [],
      "Judo Throw": [],
      "Flying Mare": [],
      "Flying Buster Drop": [],
      "Drive Impact: Blitz Combination": [],
      "Drive Reversal: Strike Eagle": [],
      "Drive Parry": [],
      "Drive Rush": [],
      "Taunt": [],
      "LP Sonic Boom": [],
      "MP Sonic Boom": [],
      "HP Sonic Boom": [],
      "OD Sonic Boom": [],
      "LK Somersault Kick": [],
      "MK Somersault Kick": [],
      "HK Somersault Kick": [],
      "OD Somersault Kick": [],
      "LP Sonic Blade": [],
      "MP Sonic Blade": [],
      "HP Sonic Blade": [],
      "Sonic Blade > Sonic Cross": [],
      "Sonic Blade > OD Sonic Cross": [],
      "OD Sonic Blade": [],
      "OD Sonic Blade > Sonic Cross": [],
      "OD Sonic Blade > OD Sonic Cross": [],
      "Sonic Hurricane": [],
      "Solid Puncher": [],
      "Crossfire Somersault": [],
      "Crossfire Somersault (Critical Art)": []
    },
    "sonic-puncher": {
      "Sonic Break": [],
      "Sonic Break Follow-up": [],
      "OD Sonic Break Follow-up": []
    }
  })
}