const data = {
  "base": {
    "Stand LP": [{c:4}, {hap:3}, {pc:7}],
    "Stand MP": [{c:6}, {hap:3}, {pc:15}],
    "Stand HP": [{c:6}, {hap:3}, {pc:23}],
    "Stand LK": [{c:4}, {hap:2}, {pc:12}],
    "Stand MK": [{c:6}, {hap:5}, {pc:18}],
    "Stand HK": [{c:12}, {hap:3}, {pc:21}],
    "Crouch LP": [{c:3}, {hap:3}, {pc:8}],
    "Crouch MP": [{c:5}, {hap:3}, {pc:16}],
    "Crouch HP": [{c:8}, {hap:5}, {pc:20}],
    "Crouch LK": [{c:4}, {hap:2}, {pc:13}],
    "Crouch MK": [{c:7}, {hap:3}, {pc:18}],
    "Crouch HK": [{c:8}, {hap:2}, {pc:16}, {hap:3}, {pc:21}],
    "Jump LP": [{c:3}, {hap:10}],
    "Jump MP": [{c:6}, {hap:3}],
    "Jump HP": [{c:8}, {hap:4}],
    "Jump LK": [{c:5}, {hap:10}],
    "Jump MK": [{c:6}, {hap:7}],
    "Jump HK": [{c:9}, {hap:5}],
    "Full Bullet Magnum": [{c:19}, {hap:3}, {pc:19}],
    "Spinning Back Knuckle": [{c:15}, {hap:3}, {pc:20}],
    "Burning Straight": [{c:8}, {hap:3}, {pc:21}],
    "Knee Bazooka": [{c:7}, {hap:5}, {pc:15}],
    "Rolling Sobat": [{c:10}, {hap:3}, {pc:18}],
    "Reverse Spin Kick": [{c:16}, {hap:3}, {pc:26}],
    "Guile High Kick": [{c:9}, {hap:3}, {pc:23}],
    "Recoil Cannon": [{c:6}, {hap:3}, {pc:1}, {c:15}, {hap:3}, {pc:26}],
    "Double Shot": [{c:5}, {hap:3}, {pc:1}, {c:11}, {hap:3}, {pc:16}],
    "Drake Fang": [{c:7}, {hap:1}, {pc:19}, {hap:3}, {pc:21}],
    "Phantom Cutter": [{c:8}, {hap:2}, {pc:10}, {c:9}, {hap:3}, {pc:25}],
    "Dragon Suplex": [{c:4}, {hap:3}, {pc:23}],
    "Judo Throw": [{c:4}, {hap:3}, {pc:23}],
    "Flying Mare": [{c:4}, {hap:3}],
    "Flying Buster Drop": [{c:4}, {hap:3}],
    "Drive Impact: Blitz Combination": [{pcat:25}, {hap:3}, {pc:35}],
    "Drive Reversal: Strike Eagle": [{ip:19}, {hap:3}, {pc:26}],
    "Drive Parry": [{c:45}],
    "Drive Rush": [{c:45}],
    "Taunt": [],
    "LP Sonic Boom": [{c:9}, {pat:31}],
    "MP Sonic Boom": [{c:9}, {pat:31}],
    "HP Sonic Boom": [{c:9}, {pat:31}],
    "OD Sonic Boom": [{c:9}, {pat:29}],
    "LK Somersault Kick": [{c:4}, {hap:6}, {pc:41}],
    "MK Somersault Kick": [{c:5}, {hap:6}, {pc:42}],
    "HK Somersault Kick": [{c:6}, {hap:6}, {pc:43}],
    "OD Somersault Kick": [{ip:5}, {hap:6}, {pc:46}],
    "LP Sonic Blade": [{c:15}, {pat:27}],
    "MP Sonic Blade": [{c:20}, {pat:30}],
    "HP Sonic Blade": [{c:30}, {pat:24}],
    "Sonic Blade > Sonic Cross": [{c:15}, {pat:19}, {pc:9}, {hap:29}],
    "Sonic Blade > OD Sonic Cross": [{c:15}, {pat:19}, {pc:9}, {hap:29}],
    "OD Sonic Blade": [{c:14}, {pat:25}],
    "OD Sonic Blade > Sonic Cross": [{c:14}, {pat:19}, {pc:9}, {hap:29}],
    "OD Sonic Blade > OD Sonic Cross": [{c:14}, {pat:19}, {pc:9}, {hap:29}],
    "Sonic Hurricane": [{sip:7}, {pat:51}, {pc:31}],
    "Solid Puncher": [{c:6}],
    "Crossfire Somersault": [{ip:8}, {hap:6}, {pc:70}],
    "Crossfire Somersault (Critical Art)": [{ip:8}, {hap:6}, {pc:70}]
  },
  "sonic-puncher": {
    "Sonic Break": [{c:10}, {pat:26}],
    "Sonic Break Follow-up": [{c:10}, {pat:2}, {pc:10}, {pat:26}],
    "OD Sonic Break Follow-up": [{c:9}, {pat:2}, {pc:10}, {pat:25}]
  }
}

export default data;