const data = {
  "base": {
    "Stand LP": [{c:5}, {hap:3}, {pc:10}],
    "Stand MP": [{c:11}, {hap:3}, {pc:21}],
    "Stand HP": [{c:11}, {hap:2}, {pc:22}],
    "Stand LK": [{c:4}, {hap:3}, {pc:11}],
    "Stand MK": [{c:7}, {hap:3}, {pc:19}],
    "Stand HK": [{c:11}, {hap:4}, {pc:17}],
    "Crouch LP": [{c:3}, {hap:2}, {pc:11}],
    "Crouch MP": [{c:6}, {hap:4}, {pc:14}],
    "Crouch HP": [{c:8}, {hap:6}, {pc:20}],
    "Crouch LK": [{c:5}, {hap:2}, {pc:10}],
    "Crouch MK": [{c:8}, {hap:3}, {pc:17}],
    "Crouch HK": [{c:9}, {hap:3}, {pc:21}],
    "Jump LP": [{c:4}, {hap:10}],
    "Jump MP": [{c:11}, {hap:3}],
    "Jump HP": [{c:8}, {hap:5}],
    "Jump LK": [{c:5}, {hap:8}],
    "Jump MK": [{c:6}, {hap:6}],
    "Jump HK": [{c:10}, {hap:6}],
    "Guillotinna": [{c:21}, {hap:2}, {pc:19}],
    "Malice": [{c:15}, {hap:3}, {pc:31}],
    "Bylina": [{c:10}, {hap:6}, {pc:24}],
    "Grom Strelka First": [{c:7}, {hap:3}, {pc:16}],
    "Grom Strelka": [{c:7}, {hap:3}, {pc:6}, {c:9}, {hap:3}, {pc:20}],
    "Zilant": [{c:11}, {hap:1}, {c:19}, {hap:3}, {pc:20}],
    "Zilant Mid": [{c:11}, {hap:1}, {c:19}, {hap:3}, {pc:4}, {c:20}, {hap:3}, {pc:22}],
    "Zilant Low": [{c:11}, {hap:1}, {c:19}, {hap:3}, {pc:4}, {c:20}, {hap:3}, {pc:22}],
    "Ravina": [{c:4}, {hap:3}, {pc:23}],
    "Uragan": [{c:4}, {hap:3}, {pc:23}],
    "Tornado": [{c:4}, {hap:3}],
    "Drive Impact: Espada": [{pcat:25}, {hap:2}, {pc:35}],
    "Drive Reversal: Exilio": [{ip:19}, {hap:3}, {pc:26}],
    "Drive Parry": [{c:45}],
    "Drive Rush": [{c:45}],
    "Taunt": [],
    "Triglav": [{c:21}, {pat:10}, {pc:24}],
    "OD Triglav": [{c:19}, {pat:20}, {pc:14}],
    "LP Stribog": [{c:15}, {hap:3}, {pat:3}, {pc:28}],
    "MP Stribog": [{c:19}, {hap:3}, {pc:1}, {pat:3}, {pc:28}],
    "HP Stribog": [{c:27}, {hap:3}, {pc:9}, {pat:3}, {pc:19}],
    "OD Stribog": [{c:18}, {hap:3}, {pc:6}, {pat:3}, {pc:22}],
    "Departure": [{c:50}],
    "OD Departure": [{c:40}],
    "Departure: Window": [{c:5}, {ip:20}, {pc:19}],
    "Departure: Shadow": [{c:19}, {pc:21}],
    "OD Departure: Shadow": [{c:19}, {pc:21}],
    "LK Torbalan": [{c:13}, {pc:29}, {pat:6}, {pc:2}],
    "MK Torbalan": [{c:13}, {pat:33}, {pc:4}],
    "HK Torbalan": [{c:13}, {pat:33}, {pc:4}],
    "OD Torbalan": [{c:13}, {pc:29}, {pat:6}, {pc:2}],
    "Torbalan (Feint)": [{c:34}], 
    "Embrace": [{c:25}, {pc:26}, {hap:3}, {pc:44}],
    "OD Embrace": [{c:25}, {pc:25}, {hap:3}, {pc:44}],
    "Amnesia": [{c:2}, {pcat:18}, {pc:35}],
    "Amnesia: Bomb": [],
    "OD Amnesia": [{pcat:20}, {pc:35}],
    "OD Amnesia: Bomb": [],
    "Chornobog": [{sip:7}, {hap:14}, {pat:22}, {pc:41}],
    "Lovushka": [{c:13}],
    "Interdiction": [{ip:17}, {hap:6}, {pc:62}],
    "Interdiction (Critical Art)": [{ip:17}, {hap:6}, {pc:62}]
  }
}
export default data;