export default function JP() {
  return ({
    "base": {
      "Stand LP": [],
      "Stand MP": [],
      "Stand HP": [],
      "Stand LK": [],
      "Stand MK": [],
      "Stand HK": [],
      "Crouch LP": [],
      "Crouch MP": [],
      "Crouch HP": [],
      "Crouch LK": [],
      "Crouch MK": [],
      "Crouch HK": [],
      "Jump LP": [],
      "Jump MP": [],
      "Jump HP": [],
      "Jump LK": [],
      "Jump MK": [],
      "Jump HK": [],
      "Guillotinna": [],
      "Malice": [],
      "Bylina": [],
      "Grom Strelka First": [],
      "Grom Strelka": [],
      "Zilant": [],
      "Zilant Mid": [],
      "Zilant Low": [],
      "Ravina": [],
      "Uragan": [],
      "Tornado": [],
      "Drive Impact: Espada": [],
      "Drive Reversal: Exilio": [],
      "Drive Parry": [],
      "Drive Rush": [],
      "Taunt": [],
      "Triglav": [],
      "OD Triglav": [],
      "LP Stribog": [],
      "MP Stribog": [],
      "HP Stribog": [],
      "OD Stribog": [],
      "Departure": [],
      "OD Departure": [],
      "Departure: Window": [],
      "Departure: Shadow": [],
      "OD Departure: Shadow": [],
      "LK Torbalan": [],
      "MK Torbalan": [],
      "HK Torbalan": [],
      "OD Torbalan": [],
      "Torbalan (Feint)": [],
      "Embrace": [],
      "OD Embrace": [],
      "Amnesia": [],
      "Amnesia: Bomb": [],
      "OD Amnesia": [],
      "OD Amnesia: Bomb": [],
      "Chornobog": [],
      "Lovushka": [],
      "Interdiction": [],
      "Interdiction (Critical Art)": []
    }
  })
}