const data = {
  "base": {
    "Stand LP": [],
    "Stand MP": [],
    "Stand HP": [],
    "Stand LK": [],
    "Stand MK": [],
    "Stand HK": [],
    "Crouch LP": [],
    "Crouch MP": [],
    "Crouch HP": [],
    "Crouch LK": [],
    "Crouch MK": [],
    "Crouch HK": [],
    "Jump LP": [],
    "Jump MP": [],
    "Jump HP": [],
    "Jump LK": [],
    "Jump MK": [],
    "Jump HK": [],
    "Neutral Jump HK": [],
    "Kyosesho": [],
    "Senkai Kick": [],
    "Renko Kicks": [],
    "Korenzan": [],
    "Death Crest 1": [],
    "Death Crest 2": [],
    "Spider Fang Throw": [],
    "Shadow Kick Throw": [],
    "Zanka-sen": [],
    "Drive Impact: Sekkan Kick": [],
    "Drive Reversal: Kaita Raid": [],
    "Drive Parry": [],
    "Drive Rush": [],
    "Taunt": [],
    "LK Fuhajin": [],
    "MK Fuhajin": [],
    "HK Fuhajin": [],
    "OD Fuhajin": [],
    "Saihasho": [],
    "Saihasho (stock)": [],
    "OD Saihasho": [],
    "Ankensatsu": [],
    "Ankensatsu (stock)": [],
    "OD Ankensatsu": [],
    "Go Ohsatsu": [],
    "Go Ohsatsu (stock)": [],
    "OD Go Ohsatsu": [],
    "LP Tenserin": [],
    "MP Tenserin": [],
    "HP Tenserin": [],
    "OD Tenserin": [],
    "Shiku-sen": [],
    "OD Shiku-sen": [],
    "> Shiren-sen": [],
    "> OD Shiren-sen": [],
    "Sakkai Fuhazan (0 stock)": [],
    "Sakkai Fuhazan (1 stock)": [],
    "Feng Shui Engine": [],
    "Feng Shui Engine (dash)": [],
    "Kaisen Dankai Raku": [],
    "Kaisen Dankai Raku (Critical Art)": []
  },
  "feng-shui-engine": {
    "Stand LP": [],
    "Stand MP": [],
    "Stand HP": [],
    "Stand LK": [],
    "Stand MK": [],
    "Stand HK": [],
    "Crouch LP": [],
    "Crouch MP": [],
    "Crouch HP": [],
    "Crouch LK": [],
    "Crouch MK": [],
    "Crouch HK": [],
    "Jump LP": [],
    "Jump MP": [],
    "Jump HP": [],
    "Jump LK": [],
    "Jump MK": [],
    "Jump HK": [],
    "Neutral Jump HK": [],
    "Kyosesho": [],
    "Senkai Kick": [],
    "Renko Kicks": [],
    "Korenzan": [],
    "Death Crest 1": [],
    "Death Crest 2": []
  }
}
export default data;