const data = {
  "base": {
    "Stand LP": [{c:3}, {hap:4}, {pc:7}],
    "Stand MP": [{c:5}, {hap:4}, {pc:12}],
    "Stand HP": [{c:9}, {hap:3}, {pc:24}],
    "Stand LK": [{c:4}, {hap:3}, {pc:9}],
    "Stand MK": [{c:4}, {hap:2}, {pc:1}, {hap:3}, {pc:17}],
    "Stand HK": [{c:17}, {hap:6}, {pc:62}],
    "Crouch LP": [{c:3}, {hap:3}, {pc:8}],
    "Crouch MP": [{c:5}, {hap:4}, {pc:14}],
    "Crouch HP": [{c:7}, {hap:4}, {pc:23}],
    "Crouch LK": [{c:4}, {hap:3}, {pc:8}],
    "Crouch MK": [{c:7}, {hap:3}, {pc:19}],
    "Crouch HK": [{c:9}, {hap:3}, {pc:23}],
    "Jump LP": [{c:4}, {hap:6}],
    "Jump MP": [{c:6}, {hap:5}],
    "Jump HP": [{c:11}, {hap:6}],
    "Jump LK": [{c:3}, {hap:6}],
    "Jump MK": [{c:5}, {hap:6}],
    "Jump HK": [{c:9}, {hap:6}],
    "Neutral Jump HK": [{c:9}, {hap:4}],
    "Kyosesho": [{c:7}, {hap:3}, {pc:17}],
    "Senkai Kick": [{c:20}, {hap:2}, {pc:23}],
    "Renko Kicks": [{c:14}, {hap:3}, {pc:5}, {hap:3}, {pc:20}],
    "Korenzan": [{c:9}, {hap:3}, {pc:6}, {hap:3}, {pc:19}],
    "Death Crest 1": [{c:5}, {hap:4}, {pc:4}, {c:11}, {hap:3}, {pc:20}],
    "Death Crest 2": [{c:5}, {hap:4}, {pc:4}, {c:11}, {hap:1}, {c:16}, {hap:3}, {pc:27}],
    "Spider Fang Throw": [{c:4}, {hap:3}, {pc:23}],
    "Shadow Kick Throw": [{c:4}, {hap:3}, {pc:23}],
    "Zanka-sen": [{c:4}, {hap:3}, {pc:23}],
    "Drive Impact: Sekkan Kick": [{pcat:25}, {hap:2}, {pc:35}],
    "Drive Reversal: Kaita Raid": [{ip:19}, {hap:3}, {pc:31}],
    "Drive Parry": [{pcat:12}, {pc:33}],
    "Drive Rush": [{c:45}],
    "Taunt": [],
    "LK Fuhajin": [{c:9}, {hap:4}, {pc:21}],
    "MK Fuhajin": [{c:12}, {hap:4}, {pc:21}],
    "HK Fuhajin": [{c:24}, {hap:4}, {pc:20}],
    "OD Fuhajin": [{c:12}, {hap:6}, {pc:21}],
    "Saihasho": [{c:15}, {pat:10}, {pc:20}],
    "Saihasho (stock)": [{c:15}, {hap:30}],
    "OD Saihasho": [{c:11}, {pat:28}],
    "Ankensatsu": [{c:23}, {hap:4}, {pc:19}],
    "Ankensatsu (stock)": [{c:23}, {hap:4}, {pc:19}],
    "OD Ankensatsu": [{c:23}, {hap:4}, {pc:19}],
    "Go Ohsatsu": [{c:17}, {hap:4}, {pc:27}],
    "Go Ohsatsu (stock)": [{c:17}, {hap:4}, {pc:12}, {hap:3}, {pc:27}],
    "OD Go Ohsatsu": [{c:17}, {hap:4}, {pc:12}, {hap:3}, {pc:28}, {hap:5}, {pc:28}],
    "LP Tenserin": [{c:10}, {hap:3}, {pc:2}, {hap:2}, {pc:22}],
    "MP Tenserin": [{c:4}, {hap:8}, {pc:5}, {hap:2}, {pc:3}, {hap:2}, {pc:38}],
    "HP Tenserin": [{c:4}, {hap:8}, {pc:5}, {hap:2}, {pc:3}, {hap:2}, {pc:38}],
    "OD Tenserin": [{ip:5}, {hap:4}, {pc:1}, {hap:2}, {pc:6}, {hap:2}, {pc:2}, {hap:2}, {pc:51}],
    "Shiku-sen": [{c:17}, {hap:5}, {pc:18}],
    "OD Shiku-sen": [{c:15}, {hap:6}, {pc:18}],
    "> Shiren-sen": [{c:17}, {hap:1}, {c:5}, {hap:4}, {pc:4}, {hap:4}, {pc:17}, {hap:4}, {pc:38}],
    "> OD Shiren-sen": [{c:17}, {hap:1}, {c:5}, {hap:4}, {pc:4}, {hap:4}, {pc:17}, {hap:4}, {pc:37}],
    "Sakkai Fuhazan (0 stock)": [{sip:6}, {pat:42}, {pc:13}, {pat:35}, {pc:42}, {pat:5}, {pc:58}],
    "Sakkai Fuhazan (1 stock)": [{sip:6}, {pat:42}, {pc:13}, {pat:35}, {pc:42}, {pat:5}, {pc:58}],
    "Feng Shui Engine": [{c:7}],
    "Feng Shui Engine (dash)": [{c:8}, {hap:11}, {pc:26}],
    "Kaisen Dankai Raku": [{ip:9}, {hap:4}, {pc:52}],
    "Kaisen Dankai Raku (Critical Art)": [{ip:9}, {hap:4}, {pc:52}]
  },
  "feng-shui-engine": {
    "Stand LP": [{c:3}, {hap:4}, {pc:7}],
    "Stand MP": [{c:5}, {hap:4}, {pc:12}],
    "Stand HP": [{c:9}, {hap:3}, {pc:24}],
    "Stand LK": [{c:4}, {hap:3}, {pc:9}],
    "Stand MK": [{c:4}, {hap:2}, {pc:1}, {hap:3}, {pc:17}],
    "Stand HK": [{c:17}, {hap:6}, {pc:62}],
    "Crouch LP": [{c:3}, {hap:3}, {pc:8}],
    "Crouch MP": [{c:5}, {hap:4}, {pc:14}],
    "Crouch HP": [{c:7}, {hap:4}, {pc:23}],
    "Crouch LK": [{c:4}, {hap:3}, {pc:8}],
    "Crouch MK": [{c:7}, {hap:3}, {pc:19}],
    "Crouch HK": [{c:9}, {hap:3}, {pc:23}],
    "Jump LP": [{c:4}, {hap:6}],
    "Jump MP": [{c:6}, {hap:5}],
    "Jump HP": [{c:11}, {hap:6}],
    "Jump LK": [{c:3}, {hap:6}],
    "Jump MK": [{c:5}, {hap:6}],
    "Jump HK": [{c:9}, {hap:6}],
    "Neutral Jump HK": [{c:9}, {hap:4}],
    "Kyosesho": [{c:7}, {hap:3}, {pc:17}],
    "Senkai Kick": [{c:20}, {hap:2}, {pc:23}],
    "Renko Kicks": [{c:14}, {hap:3}, {pc:5}, {hap:3}, {pc:20}],
    "Korenzan": [{c:9}, {hap:3}, {pc:6}, {hap:3}, {pc:19}],
    "Death Crest 1": [{c:5}, {hap:4}, {pc:4}, {c:11}, {hap:3}, {pc:20}],
    "Death Crest 2": [{c:5}, {hap:4}, {pc:4}, {c:11}, {hap:1}, {c:16}, {hap:3}, {pc:27}],
  }
}
export default data;