const data = {
  "base": {
    "Stand LP": [{c:3}, {hap:3}, {pc:7}],
    "Stand MP": [{c:4}, {hap:4}, {pc:14}],
    "Stand HP": [{c:9}, {hap:5}, {pc:17}],
    "Stand LK": [{c:4}, {hap:2}, {pc:12}],
    "Stand MK": [{c:7}, {hap:3}, {pc:20}],
    "Stand HK": [{c:11}, {hap:2}, {pc:25}],
    "Crouch LP": [{c:3}, {hap:2}, {pc:9}],
    "Crouch MP": [{c:5}, {hap:3}, {pc:14}],
    "Crouch HP": [{c:7}, {hap:4}, {pc:24}],
    "Crouch LK": [{c:4}, {hap:3}, {pc:10}],
    "Crouch MK": [{c:6}, {hap:3}, {pc:19}],
    "Crouch HK": [{c:7}, {hap:3}, {pc:24}],
    "Jump LP": [{c:4}, {hap:7}],
    "Jump MP": [{c:5}, {hap:4}],
    "Jump HP": [{c:8}, {hap:6}],
    "Jump LK": [{c:5}, {hap:6}],
    "Jump MK": [{c:6}, {hap:6}],
    "Jump HK": [{c:9}, {hap:7}],
    "Neutral Jump HK": [{c:5}, {hap:6}],
    "Chin Buster 2nd": [{c:4}, {hap:4}, {pc:1}, {c:10}, {hap:3}, {pc:27}],
    "Triple Flash Kicks 1": [{c:7}, {hap:3}, {pc:4}, {c:10}, {hap:2}, {pc:27}],
    "Triple Flash Kicks 2": [{c:7}, {hap:3}, {pc:4}, {c:10}, {hap:2}, {pc:16}, {hap:3}, {pc:28}],
    "Knee Strikes": [{c:4}, {hap:3}, {pc:23}],
    "Hell Wheel": [{c:4}, {hap:3}, {pc:23}],
    "Drive Impact: Flame Strike": [{pcat:25}, {hap:2}, {pc:35}],
    "Drive Reversal: Lightning Crack": [{ip:19}, {hap:3}, {pc:31}],
    "Drive Parry": [{pcat:12}, {pc:33}],
    "Drive Rush": [{c:38}],
    "Taunt": [],
    "LP Hadoken": [{pc:15}, {pat:34}],
    "MP Hadoken": [{pc:15}, {pat:36}],
    "HP Hadoken": [{pc:15}, {pat:38}],
    "OD Hadoken": [{pc:11}, {pat:29}],
    "LP Shoryuken": [{c:4}, {hap:10}, {pc:33}],
    "MP Shoryuken": [{c:5}, {hap:10}, {pc:30}],
    "HP Shoryuken": [{c:4}, {pip:2}, {hap:10}, {pc:50}],
    "OD Shoryuken": [{ip:5}, {hap:10}, {pc:14}, {hap:10}, {pc:50}],
    "LK Tatsumaki Senpukyaku": [{c:3}, {hap:2}, {pc:6}, {hap:3}, {pc:32}],
    "MK Tatsumaki Senpukyaku": [{c:13}, {hap:2}, {pc:13}, {hap:2}, {pc:31}],
    "HK Tatsumaki Senpukyaku": [{c:15}, {hap:2}, {pc:13}, {hap:2}, {pc:13}, {hap:2}, {pc:31}],
    "OD Tatsumaki Senpukyaku": [{c:9}, {hap:4}, {pc:5}, {hap:3}, {pc:6}, {hap:3}, {pc:6}, {hap:3}, {pc:15}, {hap:3}, {pc:34}],
    "Air Tatsumaki Senpukyaku": [{c:10}, {hap:2}, {pc:5}, {hap:2}, {pc:6}, {hap:2}],
    "OD Air Tatsumaki Senpukyaku": [{c:10}, {hap:2}, {pc:1}, {hap:2}, {pc:2}, {hap:2}, {pc:2}, {hap:2}, {pc:3}, {hap:2}, {pc:28}],
    "LK Dragonlash Kick": [{c:17}, {hap:6}, {pc:21}],
    "MK Dragonlash Kick": [{c:22}, {hap:5}, {pc:25}],
    "HK Dragonlash Kick": [{c:27}, {hap:5}, {pc:21}],
    "OD Dragonlash Kick": [{c:8}, {hap:2}, {c:7}, {hap:6}, {pc:24}],
    "LK Jinrai Kick": [{c:11}, {hap:3}, {pc:28}],
    "MK Jinrai Kick": [{c:15}, {hap:3}, {pc:24}],
    "HK Jinrai Kick": [{c:24}, {hap:3}, {pc:19}],
    "Kazekama Shin Kick": [{c:11}, {hap:3}, {pc:22}, {hap:4}, {pc:19}],
    "Gorai Axe Kick": [{c:11}, {hap:3}, {pc:34}, {hap:3}, {pc:20}],
    "Senka Snap Kick": [{c:11}, {hap:3}, {pc:24}, {hap:3}, {pc:25}],
    "OD Jinrai Kick": [{c:12}, {hap:5}, {pc:25}],
    "OD Kazekama Shin Kick": [{c:12}, {hap:5}, {pc:10}, {hap:3}, {pc:20}],
    "OD Gorai Axe Kick": [{c:12}, {hap:5}, {pc:21}, {hap:3}, {pc:24}],
    "OD Senka Snap Kick": [{c:12}, {hap:5}, {pc:12}, {hap:3}, {pc:20}],
    "OD Kasai Thrust Kick (LK)": [{c:12}, {hap:5}, {pc:10}, {hap:3}, {pc:16}, {hap:3}, {pc:29}],
    "OD Kasai Thrust Kick (MK)": [{c:12}, {hap:5}, {pc:21}, {hap:3}, {pc:14}, {hap:3}, {pc:29}],
    "OD Kasai Thrust Kick (HK)": [{c:12}, {hap:5}, {pc:12}, {hap:3}, {pc:22}, {hap:3}, {pc:37}],
    "Quick Dash": [{c:45}],
    "Emergency Stop": [{c:27}],
    "Thunder Kick": [{c:28}, {hap:3}, {pc:20}],
    "Forward Step Kick": [{c:20}, {hap:4}, {pc:20}],
    "Run > Shoryuken": [{c:13}, {pip:5}, {hap:11}, {pc:48}],
    "Run > Tatsumaki Senpukyaku": [{c:23}, {hap:2}, {pc:2}, {hap:3}, {pc:2}, {hap:2}, {pc:2}, {hap:3}, {pc:2}, {hap:2}, {pc:2}, {hap:3}, {pc:2}, {hap:2}, {pc:2}, {hap:3}, {pc:2}, {hap:2}, {pc:5}, {hap:3}, {pc:20}],
    "Run > Dragonlash": [{c:19}, {hap:4}, {c:5}, {hap:6}, {pc:24}],
    "Dragonlash Flame": [{sip:6}, {hap:3}, {pc:41}],
    "Shippu Jinrai-kyaku": [{c:5}, {hap:2}, {pc:10}, {hap:3}, {pc:10}, {hap:3}, {pc:12}, {hap:3}, {pc:11}, {hap:2}, {pc:32}],
    "Shinryu Reppa": [{ip:6}, {hap:3}, {ip:1}, {hap:6}, {ip:2}, {pc:14}, {hap:13}, {pc:45}],
    "Shinryu Reppa (Critical Art)": [{ip:6}, {hap:3}, {ip:1}, {hap:6}, {ip:2}, {pc:14}, {hap:13}, {pc:45}]
  }
}
export default data;