const data = {
  "base": {
    "Stand LP": [],
    "Stand MP": [],
    "Stand HP": [],
    "Stand LK": [],
    "Stand MK": [],
    "Stand HK": [],
    "Crouch LP": [],
    "Crouch MP": [],
    "Crouch HP": [],
    "Crouch LK": [],
    "Crouch MK": [],
    "Crouch HK": [],
    "Jump LP": [],
    "Jump MP": [],
    "Jump HP": [],
    "Jump LK": [],
    "Jump MK": [],
    "Jump HK": [],
    "Neutral Jump HK": [],
    "Chin Buster 2nd": [],
    "Triple Flash Kicks 1": [],
    "Triple Flash Kicks 2": [],
    "Knee Strikes": [],
    "Hell Wheel": [],
    "Drive Impact: Flame Strike": [],
    "Drive Reversal: Lightning Crack": [],
    "Drive Parry": [],
    "Drive Rush": [],
    "Taunt": [],
    "LP Hadoken": [],
    "MP Hadoken": [],
    "HP Hadoken": [],
    "OD Hadoken": [],
    "LP Shoryuken": [],
    "MP Shoryuken": [],
    "HP Shoryuken": [],
    "OD Shoryuken": [],
    "LK Tatsumaki Senpukyaku": [],
    "MK Tatsumaki Senpukyaku": [],
    "HK Tatsumaki Senpukyaku": [],
    "OD Tatsumaki Senpukyaku": [],
    "Air Tatsumaki Senpukyaku": [],
    "OD Air Tatsumaki Senpukyaku": [],
    "LK Dragonlash Kick": [],
    "MK Dragonlash Kick": [],
    "HK Dragonlash Kick": [],
    "OD Dragonlash Kick": [],
    "LK Jinrai Kick": [],
    "MK Jinrai Kick": [],
    "HK Jinrai Kick": [],
    "Kazekama Shin Kick": [],
    "Gorai Axe Kick": [],
    "Senka Snap Kick": [],
    "OD Jinrai Kick": [],
    "OD Kazekama Shin Kick": [],
    "OD Gorai Axe Kick": [],
    "OD Senka Snap Kick": [],
    "OD Kasai Thrust Kick (LK)": [],
    "OD Kasai Thrust Kick (MK)": [],
    "OD Kasai Thrust Kick (HK)": [],
    "Quick Dash": [],
    "Emergency Stop": [],
    "Thunder Kick": [],
    "Forward Step Kick": [],
    "Run > Shoryuken": [],
    "Run > Tatsumaki Senpukyaku": [],
    "Run > Dragonlash": [],
    "Dragonlash Flame": [],
    "Shippu Jinrai-kyaku": [],
    "Shinryu Reppa": [],
    "Shinryu Reppa (Critical Art)": []
  }
}
export default data;