const data = {
  "base": {
    "Stand LP": [],
    "Stand MP": [],
    "Stand HP": [],
    "Stand LK": [],
    "Stand MK": [],
    "Stand HK": [],
    "Crouch LP": [],
    "Crouch MP": [],
    "Crouch HP": [],
    "Crouch LK": [],
    "Crouch MK": [],
    "Crouch HK": [],
    "Jump LP": [],
    "Jump MP": [],
    "Jump HP": [],
    "Jump LK": [],
    "Jump MK": [],
    "Jump HK": [],
    "Elbow Drop": [],
    "Water Slicer Slide": [],
    "Windmill Kick": [],
    "Hisen Kick": [],
    "Step Up (neutral hop)": [],
    "Step Up (forward hop)": [],
    "Step Up (backward hop)": [],
    "Bushin Prism Strikes 1": [],
    "Bushin Prism Strikes 2": [],
    "Bushin Prism Strikes 3": [],
    "Bushin Hellchain 1": [],
    "Bushin Hellchain 2": [],
    "Bushin Hellchain Throw": [],
    "Bushin Tiger Fangs": [],
    "Ripcord Throw": [],
    "Bell Ringer": [],
    "Drive Impact: Steadfast Strike": [],
    "Drive Reversal: Shapeless State": [],
    "Drive Parry": [],
    "Drive Rush": [],
    "Taunt": [],
    "LK Bushin Senpukyaku": [],
    "MK Bushin Senpukyaku": [],
    "HK Bushin Senpukyaku": [],
    "OD Bushin Senpukyaku": [],
    "Aerial Bushin Senpukyaku": [],
    "OD Aerial Bushin Senpukyaku": [],
    "LP Vagabond Edge": [],
    "MP Vagabond Edge": [],
    "HP Vagabond Edge": [],
    "OD Vagabond Edge": [],
    "Sprint": [],
    "OD Sprint": [],
    "Sprint > Torso Cleaver": [],
    "Sprint > Shadow Slide": [],
    "Sprint > Neck Hunter": [],
    "Sprint > Emergency Stop": [],
    "Sprint > Arc Step": [],
    "Arc Step > Bushin Hojin Kick": [],
    "Arc Step > Bushin Izuna Otoshi": [],
    "OD Sprint > Torso Cleaver": [],
    "OD Sprint > Shadow Slide": [],
    "OD Sprint > Neck Hunter": [],
    "OD Sprint > Emergency Stop": [],
    "OD Sprint > Arc Step": [],
    "OD Arc Step > Bushin Hojin Kick": [],
    "OD Arc Step > Bushin Izuna Otoshi": [],
    "Hidden Variable": [],
    "OD Hidden Variable": [],
    "Genius at Play": [],
    "OD Genius at Play": [],
    "Shuriken Bomb": [],
    "Shuriken Bomb Spread": [],
    "Nue Twister": [],
    "OD Nue Twister": [],
    "Bushin Beats (0 stock)": [],
    "Bushin Beats (1 stock)": [],
    "Bushin Scramble": [],
    "Soaring Bushin Scramble (air)": [],
    "Bushin Ninjastar Cypher": [],
    "Bushin Ninjastar Cypher (Critical Art)": []
  },
  "bushin-ninjastar": {
    "Stand LP": [],
    "Stand MP": [],
    "Stand HP": [],
    "Stand LK": [],
    "Stand MK": [],
    "Stand HK": [],
    "Crouch LP": [],
    "Crouch MP": [],
    "Crouch HP": [],
    "Crouch LK": [],
    "Crouch MK": [],
    "Crouch HK": [],
    "Jump LP": [],
    "Jump MP": [],
    "Jump HP": [],
    "Jump LK": [],
    "Jump MK": [],
    "Jump HK": [],
    "Elbow Drop": [],
    "Water Slicer Slide": [],
    "Windmill Kick": [],
    "Hisen Kick": [],
    "Step Up (neutral hop)": [],
    "Step Up (forward hop)": [],
    "Step Up (backward hop)": [],
    "Bushin Prism Strikes 1": [],
    "Bushin Prism Strikes 2": [],
    "Bushin Prism Strikes 3": [],
    "Bushin Hellchain 1": [],
    "Bushin Hellchain 2": [],
    "Bushin Hellchain Throw": [],
    "Bushin Tiger Fangs": [],
    "Ripcord Throw": [],
    "Bell Ringer": [],
    "Drive Impact: Steadfast Strike": [],
    "Drive Reversal: Shapeless State": [],
    "Drive Parry": [],
    "Drive Rush": [],
    "Taunt": [],
    "LK Bushin Senpukyaku": [],
    "MK Bushin Senpukyaku": [],
    "HK Bushin Senpukyaku": [],
    "OD Bushin Senpukyaku": [],
    "Aerial Bushin Senpukyaku": [],
    "OD Aerial Bushin Senpukyaku": [],
    "LP Vagabond Edge": [],
    "MP Vagabond Edge": [],
    "HP Vagabond Edge": [],
    "OD Vagabond Edge": [],
    "Sprint": [],
    "OD Sprint": [],
    "Sprint > Torso Cleaver": [],
    "Sprint > Shadow Slide": [],
    "Sprint > Neck Hunter": [],
    "Sprint > Emergency Stop": [],
    "Sprint > Arc Step": [],
    "Arc Step > Bushin Hojin Kick": [],
    "Arc Step > Bushin Izuna Otoshi": [],
    "OD Sprint > Torso Cleaver": [],
    "OD Sprint > Shadow Slide": [],
    "OD Sprint > Neck Hunter": [],
    "OD Sprint > Emergency Stop": [],
    "OD Sprint > Arc Step": [],
    "OD Arc Step > Bushin Hojin Kick": [],
    "OD Arc Step > Bushin Izuna Otoshi": [],
    "Hidden Variable": [],
    "OD Hidden Variable": [],
    "Genius at Play": [],
    "OD Genius at Play": [],
    "Shuriken Bomb": [],
    "Shuriken Bomb Spread": [],
    "Nue Twister": [],
    "OD Nue Twister": [],
    "Bushin Beats (0 stock)": [],
    "Bushin Beats (1 stock)": [],
    "Bushin Scramble": [],
    "Soaring Bushin Scramble (air)": [],
    "Bushin Ninjastar Cypher": [],
    "Bushin Ninjastar Cypher (Critical Art)": []
  }
}
export default data;