const data = {
  "base": {
    "Stand LP": [{c:4}, {hap:3}, {pc:8}],
    "Stand MP": [{c:8}, {hap:4}, {pc:17}],
    "Stand HP": [{c:10}, {hap:3}, {pc:22}],
    "Stand LK": [{c:3}, {hap:4}, {pc:8}],
    "Stand MK": [{c:6}, {hap:3}, {pc:15}],
    "Stand HK": [{c:13}, {hap:4}, {pc:21}],
    "Crouch LP": [{c:5}, {hap:3}, {pc:8}],
    "Crouch MP": [{c:7}, {hap:3}, {pc:18}],
    "Crouch HP": [{c:9}, {hap:6}, {pc:22}],
    "Crouch LK": [{c:4}, {hap:2}, {pc:12}],
    "Crouch MK": [{c:8}, {hap:3}, {pc:18}],
    "Crouch HK": [{c:10}, {hap:2}, {pc:6}, {hap:2}, {pc:24}],
    "Jump LP": [{c:4}, {hap:9}],
    "Jump MP": [{c:8}, {hap:4}],
    "Jump HP": [{c:9}, {hap:6}],
    "Jump LK": [{c:5}, {hap:6}],
    "Jump MK": [{c:7}, {hap:5}],
    "Jump HK": [{c:10}, {hap:6}],
    "Great Spin": [{c:8}, {hap:11}],
    "Double Arrow": [{c:8}, {hap:4}, {pc:1}, {c:9}, {hap:1}, {pc:16}],
    "Ridge Thrust": [{c:24}, {hap:3}, {pc:18}],
    "Horn Breaker": [{c:13}, {hap:4}, {pc:18}],
    "Desert Storm 1": [{c:17}, {hap:2}, {pc:24}],
    "Desert Storm 2": [{c:17}, {hap:2}, {pc:2}, {c:19}, {hap:2}, {pc:27}],
    "Desert Storm Final": [{c:17}, {hap:2}, {pc:2}, {c:19}, {hap:1}, {c:19}, {hap:3}, {pc:42}],
    "Canyon Throw": [{c:4}, {hap:3}, {pc:23}],
    "Falling Cliff": [{c:4}, {hap:3}, {pc:23}],
    "Drive Impact: Earth's Rage": [{pcat:25}, {hap:2}, {pc:35}],
    "Drive Reversal: Cross Hammer": [{ip:19}, {hap:3}, {pc:31}],
    "Drive Parry": [{pcat:12}, {pc:33}],
    "Drive Rush": [{c:45}],
    "Taunt": [],
    "LP Condor Wind": [{c:47}],
    "LP Condor Wind (2 stocks)": [{c:90}],
    "LP Condor Wind (3 stocks)": [{c:109}],
    "MP Condor Wind": [{c:22}, {hap:4}, {pc:25}],
    "HP Condor Wind": [{c:24}, {hap:4}, {pc:25}],
    "OD Condor Wind (attack)": [{c:18}, {hap:4}, {pc:23}],
    "OD Condor Wind (hold)": [{C:40}],
    "LK Condor Spire": [{c:16}, {hap:13}, {pc:16}],
    "MK Condor Spire": [{c:20}, {hap:13}, {pc:16}],
    "HK Condor Spire": [{c:24}, {hap:13}, {pc:16}],
    "OD Condor Spire": [{c:15}, {hap:13}, {pc:16}],
    "LK Condor Spire (enhanced)": [{c:8}, {hap:5}, {pc:6}, {hap:18}, {pc:14}],
    "MK Condor Spire (enhanced)": [{c:12}, {hap:5}, {pc:6}, {hap:18}, {pc:14}],
    "HK Condor Spire (enhanced)": [{c:16}, {hap:5}, {pc:6}, {hap:18}, {pc:14}],
    "OD Condor Spire (enhanced)": [{C:8}, {HAP:24}, {PC:14}],
    "LP Tomahawk Buster": [{c:5}, {hap:11}, {pc:33}],
    "MP Tomahawk Buster": [{c:7}, {hap:12}, {pc:37}],
    "HP Tomahawk Buster": [{c:9}, {hap:14}, {pc:38}],
    "OD Tomahawk Buster": [{c:5}, {hap:12}, {pc:43}],
    "LP Tomahawk Buster (enhanced)": [{c:3}, {hap:13}, {pc:33}],
    "MP Tomahawk Buster (enhanced)": [{c:5}, {hap:14}, {pc:37}],
    "HP Tomahawk Buster (enhanced)": [{c:7}, {hap:16}, {pc:38}],
    "OD Tomahawk Buster (enhanced)": [{c:3}, {hap:14}, {pc:43}],
    "Condor Dive": [{c:11}, {hap:11}, {pc:24}],
    "OD Condor Dive": [{c:11}, {hap:10}, {pc:24}],
    "Condor Dive (enhanced)": [{c:11}, {hap:11}, {pc:24}],
    "OD Condor Dive (enhanced)": [{c:11}, {hap:10}, {pc:24}],
    "LP Mexican Typhoon": [{c:4}, {hap:3}, {pc:53}],
    "MP Mexican Typhoon": [{c:4}, {hap:3}, {pc:53}],
    "HP Mexican Typhoon": [{c:4}, {hap:3}, {pc:53}],
    "OD Mexican Typhoon": [{c:4}, {hap:3}, {pc:53}],
    "Breezing Hawk": [{sip:9}, {hap:2}, {pc:5}, {hap:2}, {pc:7}, {hap:2}, {pc:8}, {hap:2}, {pc:8}, {hap:2}, {pc:54}],
    "Thunderbird": [{ip:8}, {hap:2}, {ip:2}, {hap:18}, {ip:9}, {hap:2}, {pc:63}],
    "Thunderbird (enhanced)": [{ip:8}, {hap:25}, {ip:6}, {hap:2}, {pc:63}],
    "Soaring Thunderbird": [{ip:8}, {hap:2}, {ip:2}, {hap:18}, {ip:9}, {hap:2}, {pc:65}],
    "Soaring Thunderbird (enhanced)": [{ip:8}, {hap:25}, {ip:6}, {hap:2}, {pc:64}],
    "Raging Typhoon": [{ip:6}, {hap:2}, {pc:106}],
    "Raging Typhoon (Critical Art)": [{ip:6}, {hap:2}, {pc:106}]
  }
}
export default data;