const data = {
  "base": {
    "Stand LP": [],
    "Stand MP": [],
    "Stand HP": [],
    "Stand LK": [],
    "Stand MK": [],
    "Stand HK": [],
    "Crouch LP": [],
    "Crouch MP": [],
    "Crouch HP": [],
    "Crouch LK": [],
    "Crouch MK": [],
    "Crouch HK": [],
    "Jump LP": [],
    "Jump MP": [],
    "Jump HP": [],
    "Jump LK": [],
    "Jump MK": [],
    "Jump HK": [],
    "Great Spin": [],
    "Double Arrow": [],
    "Ridge Thrust": [],
    "Horn Breaker": [],
    "Desert Storm 1": [],
    "Desert Storm 2": [],
    "Desert Storm Final": [],
    "Canyon Throw": [],
    "Falling Cliff": [],
    "Drive Impact: Earth's Rage": [],
    "Drive Reversal: Cross Hammer": [],
    "Drive Parry": [],
    "Drive Rush": [],
    "Taunt": [],
    "LP Condor Wind": [],
    "LP Condor Wind (2 stocks)": [],
    "LP Condor Wind (3 stocks)": [],
    "MP Condor Wind": [],
    "HP Condor Wind": [],
    "OD Condor Wind (attack)": [],
    "OD Condor Wind (hold)": [],
    "LK Condor Spire": [],
    "MK Condor Spire": [],
    "HK Condor Spire": [],
    "OD Condor Spire": [],
    "LK Condor Spire (enhanced)": [],
    "MK Condor Spire (enhanced)": [],
    "HK Condor Spire (enhanced)": [],
    "OD Condor Spire (enhanced)": [],
    "LP Tomahawk Buster": [],
    "MP Tomahawk Buster": [],
    "HP Tomahawk Buster": [],
    "OD Tomahawk Buster": [],
    "LP Tomahawk Buster (enhanced)": [],
    "MP Tomahawk Buster (enhanced)": [],
    "HP Tomahawk Buster (enhanced)": [],
    "OD Tomahawk Buster (enhanced)": [],
    "Condor Dive": [],
    "OD Condor Dive": [],
    "Condor Dive (enhanced)": [],
    "OD Condor Dive (enhanced)": [],
    "LP Mexican Typhoon": [],
    "MP Mexican Typhoon": [],
    "HP Mexican Typhoon": [],
    "OD Mexican Typhoon": [],
    "Breezing Hawk": [],
    "Thunderbird": [],
    "Thunderbird (enhanced)": [],
    "Soaring Thunderbird": [],
    "Soaring Thunderbird (enhanced)": [],
    "Raging Typhoon": [],
    "Raging Typhoon (Critical Art)": []
  }
}
export default data;