const data = {
  "base": {
    "Stand LP": [{c:6}, {hap:2}, {pc:14}],
    "Stand MP": [{c:8}, {hap:4}, {pc:16}],
    "Stand HP": [{c:9}, {hap:3}, {pc:23}],
    "Stand LK": [{c:4}, {hap:2}, {pc:12}],
    "Stand MK": [{c:7}, {hap:3}, {pc:19}],
    "Stand HK": [{c:9}, {hap:7}, {pc:16}],
    "Crouch LP": [{c:3}, {hap:2}, {pc:10}],
    "Crouch MP": [{c:5}, {hap:2}, {pc:17}],
    "Crouch HP": [{c:6}, {hap:5}, {pc:24}],
    "Crouch LK": [{c:4}, {hap:3}, {pc:12}],
    "Crouch MK": [{c:7}, {hap:3}, {pc:19}],
    "Crouch HK": [{c:9}, {hap:3}, {pc:27}],
    "Jump LP": [{c:4}, {hap:9}],
    "Jump MP": [{c:8}, {hap:4}],
    "Jump HP": [{c:8}, {hap:6}],
    "Jump LK": [{c:5}, {hap:6}],
    "Jump MK": [{c:6}, {hap:6}],
    "Jump HK": [{c:9}, {hap:6}],
    "Rawhide": [{c:20}, {hap:2}, {pc:21}],
    "Suppressor": [{c:15}, {hap:3}, {pc:20}],
    "Outlaw Kick": [{c:11}, {hap:4}, {pc:24}],
    "Brutal Spike": [{c:15}, {hap:3}, {pc:19}],
    "Double Impact": [{c:15}, {hap:3}, {pc:6}, {c:10}, {hap:2}, {pc:34}],
    "Nose Breaker": [{c:7}, {hap:3}, {pc:4}, {c:8}, {hap:3}, {pc:25}],
    "Triple Impact": [{c:6}, {hap:2}, {c:7}, {hap:4}, {pc:20}],
    "Triple Impact 2": [{c:6}, {hap:2}, {c:7}, {hap:4}, {pc:1}, {c:9}, {hap:3}, {pc:27}],
    "Snapback Combo": [{c:8}, {hap:4}, {pc:1}, {c:11}, {hap:2}, {pc:23}],
    "Snapback Combo 2": [{c:8}, {hap:4}, {pc:1}, {c:11}, {hap:2}, {pc:4}, {c:10}, {hap:2}, {pc:29}],
    "Snapback Combo 3": [{c:8}, {hap:4}, {pc:1}, {c:11}, {hap:2}, {pc:4}, {c:10}, {hap:2}, {pc:4}, {c:10}, {hap:2}, {pc:27}],
    "Sweeper": [{c:4}, {hap:3}, {pc:23}],
    "Scrapper": [{c:4}, {hap:3}, {pc:23}],
    "Drive Impact: Muzzle Flash": [{pcat:25}, {hap:2}, {pc:35}],
    "Drive Reversal: Battering Ram": [{ip:19}, {hap:3}, {pc:32}],
    "Drive Parry": [{pcat:12}, {pc:33}],
    "Drive Rush": [{c:45}],
    "Taunt": [],
    "LP Sand Blast": [{c:13}, {pat:5}, {pc:29}],
    "MP Sand Blast": [{c:13}, {pat:7}, {pc:24}],
    "HP Sand Blast": [{c:19}, {pat:10}, {pc:18}],
    "OD Sand Blast": [{c:15}, {pat:18}, {pc:7}],
    "Fatal Shot": [{c:15}, {pat:6}, {pc:11}, {pat:16}, {pc:27}],
    "LP Rising Uppercut": [{c:4}, {hap:10}, {pc:34}],
    "MP Rising Uppercut": [{c:5}, {hap:10}, {pc:36}],
    "HP Rising Uppercut": [{c:8}, {hap:10}, {pc:40}],
    "OD Rising Uppercut": [{ip:5}, {hap:10}, {pc:50}],
    "Slam Dunk": [{ip:5}, {hap:10}, {pc:5}, {c:15}, {hap:3}, {pc:30}],
    "LP Flash Knuckle": [{c:12}, {hap:3}, {pc:31}],
    "LP Flash Knuckle (hold)": [{c:25}, {hap:4}, {pc:22}],
    "MP Flash Knuckle": [{c:18}, {hap:3}, {pc:27}],
    "MP Flash Knuckle (hold)": [{c:28}, {hap:4}, {pc:26}],
    "HP Flash Knuckle": [{c:21}, {hap:3}, {pc:21}],
    "HP Flash Knuckle (hold)": [{c:32}, {hap:4}, {pc:24}],
    "OD Flash Knuckle": [{c:14}, {hap:3}, {pc:39}],
    "DDT": [{c:12}, {hap:3}, {pc:2}, {hap:1}, {ip:160}],
    "Aerial Flash Knuckle": [{c:13}, {hap:5}, {pc:14}],
    "Aerial Flash Knuckle (hold)": [{c:22}, {hap:6}, {pc:35}],
    "OD Aerial Flash Knuckle": [{c:13}, {hap:6}, {pc:35}],
    "Avenger": [{c:45}],
    "Avenger > No Chaser": [{c:23}, {hap:10}, {pc:16}],
    "Avenger > Impaler": [{c:24}, {hap:8}, {pc:22}],
    "OD Avenger": [{c:2}, {pcat:33}, {pc:10}],
    "OD Avenger > No Chaser": [{c:2}, {pcat:9}, {pc:11}, {hap:10}, {pc:16}],
    "OD Avenger > Impaler": [{c:2}, {pcat:9}, {pc:12}, {hap:8}, {pc:19}],
    "Vulcan Blast": [{sip:5}, {pat:13}, {pc:1}, {pat:7}, {pc:1}, {pat:7}, {pc:23}, {pat:5}, {pc:42}],
    "Eraser": [{ip:4}, {hap:3}, {pc:51}],
    "Pale Rider": [{ip:13}, {pc:13}, {hap:4}, {pc:92}],
    "Pale Rider (Critical Art)": [{ip:13}, {pc:13}, {hap:4}, {pc:92}]
  }
}
export default data;