const data = {
  "base": {
    "Stand LP": [],
    "Stand MP": [],
    "Stand HP": [],
    "Stand LK": [],
    "Stand MK": [],
    "Stand HK": [],
    "Crouch LP": [],
    "Crouch MP": [],
    "Crouch HP": [],
    "Crouch LK": [],
    "Crouch MK": [],
    "Crouch HK": [],
    "Jump LP": [],
    "Jump MP": [],
    "Jump HP": [],
    "Jump LK": [],
    "Jump MK": [],
    "Jump HK": [],
    "Rawhide": [],
    "Suppressor": [],
    "Outlaw Kick": [],
    "Brutal Spike": [],
    "Double Impact": [],
    "Nose Breaker": [],
    "Triple Impact": [],
    "Triple Impact 2": [],
    "Snapback Combo": [],
    "Snapback Combo 2": [],
    "Snapback Combo 3": [],
    "Sweeper": [],
    "Scrapper": [],
    "Drive Impact: Muzzle Flash": [],
    "Drive Reversal: Battering Ram": [],
    "Drive Parry": [],
    "Drive Rush": [],
    "Taunt": [],
    "LP Sand Blast": [],
    "MP Sand Blast": [],
    "HP Sand Blast": [],
    "OD Sand Blast": [],
    "Fatal Shot": [],
    "LP Rising Uppercut": [],
    "MP Rising Uppercut": [],
    "HP Rising Uppercut": [],
    "OD Rising Uppercut": [],
    "Slam Dunk": [],
    "LP Flash Knuckle": [],
    "LP Flash Knuckle (hold)": [],
    "MP Flash Knuckle": [],
    "MP Flash Knuckle (hold)": [],
    "HP Flash Knuckle": [],
    "HP Flash Knuckle (hold)": [],
    "OD Flash Knuckle": [],
    "DDT": [],
    "Aerial Flash Knuckle": [],
    "Aerial Flash Knuckle (hold)": [],
    "OD Aerial Flash Knuckle": [],
    "Avenger": [],
    "Avenger > No Chaser": [],
    "Avenger > Impaler": [],
    "OD Avenger": [],
    "OD Avenger > No Chaser": [],
    "OD Avenger > Impaler": [],
    "Vulcan Blast": [],
    "Eraser": [],
    "Pale Rider": [],
    "Pale Rider (Critical Art)": []
  }
}
export default data;