export default function Manon() {
  return ({
    "base": {
      "Stand LP": [],
      "Stand MP": [],
      "Stand HP": [],
      "Stand LK": [],
      "Stand MK": [],
      "Stand HK": [],
      "Crouch LP": [],
      "Crouch MP": [],
      "Crouch HP": [],
      "Crouch LK": [],
      "Crouch MK": [],
      "Crouch HK": [],
      "Jump LP": [],
      "Jump MP": [],
      "Jump HP": [],
      "Jump LK": [],
      "Jump MK": [],
      "Jump HK": [],
      "Révérence": [],
      "Tomoe Derrière": [],
      "Back MK": [],
      "En Haut": [],
      "À Terre": [],
      "Temps Lié": [],
      "Allongé": [],
      "Ouchi Gari": [],
      "Uchi Mata": [],
      "Drive Impact: Glissade": [],
      "Drive Reversal: Écarté": [],
      "Drive Parry": [],
      "Drive Rush": [],
      "Taunt": [],
      "LP Manège Doré": [],
      "MP Manège Doré": [],
      "HP Manège Doré": [],
      "OD Manège Doré": [],
      "LK Rond-point": [],
      "MK Rond-point": [],
      "HK Rond-point": [],
      "OD Rond-point": [],
      "LK Dégagé": [],
      "MK Dégagé": [],
      "HK Dégagé": [],
      "OD Dégagé": [],
      "LP Renversé": [],
      "MP Renversé": [],
      "HP Renversé": [],
      "OD Renversé": [],
      "Grand Fouetté": [],
      "Renversé Feint": [],
      "OD Grand Fouetté": [],
      "OD Renversé Feint": [],
      "Arabesque": [],
      "Étoile": [],
      "Pas de Deux": [],
      "Pas de Deux (Critical Art)": []
    }
  })
}