const data = {
  "base": {
    "Stand LP": [{c:3}, {hap:3}, {pc:10}],
    "Stand MP": [{c:6}, {hap:4}, {pc:14}],
    "Stand HP": [{c:9}, {hap:4}, {pc:20}],
    "Stand LK": [{c:4}, {hap:2}, {pc:12}],
    "Stand MK": [{c:9}, {hap:3}, {pc:18}],
    "Stand HK": [{c:14}, {hap:3}, {pc:26}],
    "Crouch LP": [{c:3}, {hap:2}, {pc:11}],
    "Crouch MP": [{c:6}, {hap:3}, {pc:13}],
    "Crouch HP": [{c:9}, {hap:5}, {pc:21}],
    "Crouch LK": [{c:4}, {hap:2}, {pc:13}],
    "Crouch MK": [{c:7}, {hap:4}, {pc:16}],
    "Crouch HK": [{c:10}, {hap:2}, {pc:27}],
    "Jump LP": [{c:4}, {hap:10}],
    "Jump MP": [{c:7}, {hap:4}],
    "Jump HP": [{c:8}, {hap:4}],
    "Jump LK": [{c:5}, {hap:9}],
    "Jump MK": [{c:6}, {hap:6}],
    "Jump HK": [{c:10}, {hap:5}],
    "Révérence": [{c:7}, {hap:6}, {pc:17}],
    "Tomoe Derrière": [{c:10}, {hap:9}, {pc:32}],
    "Back MK": [{c:9}, {hap:4}, {pc:19}],
    "En Haut": [{c:9}, {hap:4}, {pc:4}, {c:13}, {hap:5}, {pc:21}],
    "À Terre": [{c:6}, {hap:4}, {pc:1}, {c:9}, {hap:2}, {pc:17}],
    "Temps Lié": [{c:9}, {hap:4}, {pc:4}, {c:4}, {hap:2}, {pc:20}],
    "Allongé": [{c:9}, {hap:5}, {c:3}, {hap:4}, {pc:26}],
    "Ouchi Gari": [{c:4}, {hap:3}, {pc:23}],
    "Uchi Mata": [{c:4}, {hap:3}, {pc:23}],
    "Drive Impact: Glissade": [{pcat:25}, {hap:2}, {pc:35}],
    "Drive Reversal: Écarté": [{ip:19}, {hap:3}, {pc:31}],
    "Drive Parry": [{pcat:12}, {pc:33}],
    "Drive Rush": [{c:45}],
    "Taunt": [],
    "LP Manège Doré": [{c:9}, {hap:2}, {pc:49}],
    "MP Manège Doré": [{c:7}, {hap:2}, {pc:51}],
    "HP Manège Doré": [{c:4}, {hap:2}, {pc:54}],
    "OD Manège Doré": [{c:7}, {hap:2}, {pc:51}],
    "LK Rond-point": [{c:8}, {hap:3}, {pc:2}, {hap:2}, {pc:29}],
    "MK Rond-point": [{c:10}, {hap:3}, {pc:3}, {hap:3}, {pc:27}],
    "HK Rond-point": [{c:13}, {hap:3}, {pc:3}, {hap:3}, {pc:24}],
    "OD Rond-point": [{c:7}, {hap:4}, {pc:2}, {hap:3}, {pc:30}],
    "LK Dégagé": [{c:15}, {hap:2}, {pc:10}, {hap:4}, {pc:36}],
    "MK Dégagé": [{c:15}, {hap:4}, {pc:14}, {hap:6}, {pc:22}],
    "HK Dégagé": [{c:19}, {hap:3}, {pc:24}],
    "OD Dégagé": [{c:22}, {hap:3}, {pc:22}],
    "LP Renversé": [{c:2}, {pip:19}, {hap:2}, {pc:37}],
    "MP Renversé": [{c:2}, {pip:22}, {hap:2}, {pc:34}],
    "HP Renversé": [{c:2}, {pip:26}, {hap:2}, {pc:30}],
    "OD Renversé": [{c:2}, {pip:22}, {hap:2}, {pc:34}],
    "Grand Fouetté": [{c:10}, {hap:6}, {pc:22}],
    "Renversé Feint": [{c:2}, {pip:13}, {c:18}],
    "OD Grand Fouetté": [{c:9}, {hap:6}, {pc:22}],
    "OD Renversé Feint": [{c:2}, {pip:14}, {c:18}],
    "Arabesque": [{sip:9}, {hap:4}, {pc:65}],
    "Étoile": [{ip:6}, {hap:3}, {pc:11}, {hap:7}, {pc:44}, {hap:9}, {pc:72}],
    "Pas de Deux": [{ip:6}, {hap:2}, {pc:72}],
    "Pas de Deux (Critical Art)": [{ip:6}, {hap:2}, {pc:72}]
  }
}
export default data;