export default function Marisa() {
  return ({
    "base": {
      "Stand LP": [],
      "Stand MP": [],
      "Stand HP": [],
      "Stand HP (hold)": [],
      "Stand LK": [],
      "Stand MK": [],
      "Stand HK": [],
      "Stand HK (hold)": [],
      "Crouch LP": [],
      "Crouch MP": [],
      "Crouch HP": [],
      "Crouch HP (hold)": [],
      "Crouch LK": [],
      "Crouch MK": [],
      "Crouch HK": [],
      "Crouch HK (hold)": [],
      "Jump LP": [],
      "Jump MP": [],
      "Jump HP": [],
      "Jump HP (hold)": [],
      "Jump LK": [],
      "Jump MK": [],
      "Jump HK": [],
      "Jump HK (hold)": [],
      "Volare Combo": [],
      "Caelum Arc": [],
      "Caelum Arc (hold)": [],
      "Novacula": [],
      "Novacula Swipe": [],
      "Novacula Thrust": [],
      "Malleus": [],
      "Malleus (hold)": [],
      "Malleus Breaker": [],
      "Magna Bunker": [],
      "Magna Bunker (hold)": [],
      "Knee": [],
      "Knee (hold)": [],
      "Falx Crusher": [],
      "Light Two Hitter": [],
      "Medium Two Hitter": [],
      "Heavy Two Hitter": [],
      "Mounted Grace": [],
      "Ponte Milvio": [],
      "Drive Impact: Secutor": [],
      "Drive Reversal: Love Tap": [],
      "Drive Parry": [],
      "Drive Rush": [],
      "Taunt": [],
      "LP Gladius": [],
      "LP Gladius (hold)": [],
      "MP Gladius": [],
      "MP Gladius (hold)": [],
      "HP Gladius": [],
      "HP Gladius (hold)": [],
      "OD Gladius": [],
      "OD Gladius (hold)": [],
      "LP Dimachaerus": [],
      "MP Dimachaerus": [],
      "HP Dimachaerus": [],
      "OD Dimachaerus": [],
      "LP Dimachaerus Follow-up": [],
      "MP Dimachaerus Follow-up": [],
      "HP Dimachaerus Follow-up": [],
      "OD Dimachaerus Follow-up": [],
      "LP Phalanx": [],
      "MP Phalanx": [],
      "HP Phalanx": [],
      "OD Phalanx": [],
      "LK Quadriga": [],
      "MK Quadriga": [],
      "HK Quadriga": [],
      "OD Quadriga": [],
      "Scutum": [],
      "Scutum (absorb)": [],
      "OD Scutum": [],
      "OD Scutum (absorb)": [],
      "Tonitrus 1": [],
      "Tonitrus 2": [],
      "Procella": [],
      "Enfold": [],
      "Javelin of Marisa": [],
      "Javelin of Marisa (Hold)": [],
      "Javelin of Marisa (Counter)": [],
      "Meteorite": [],
      "Goddess of the Hunt": [],
      "Goddess of the Hunt (Critical Art)": []
    }
  })
}