const data = {
  "base": {
    "Stand LP": [{c:5}, {hap:3}, {pc:11}],
    "Stand MP": [{c:6}, {hap:4}, {pc:17}],
    "Stand HP": [{c:11}, {hap:2}, {pc:23}],
    "Stand HP (hold)": [{c:25}, {hap:2}, {pc:22}],
    "Stand LK": [{c:5}, {hap:2}, {pc:14}],
    "Stand MK": [{c:10}, {hap:4}, {pc:16}],
    "Stand HK": [{c:14}, {hap:2}, {pc:25}],
    "Stand HK (hold)": [{c:26}, {hap:2}, {pc:25}],
    "Crouch LP": [{c:3}, {hap:2}, {pc:10}],
    "Crouch MP": [{c:7}, {hap:3}, {pc:16}],
    "Crouch HP": [{c:8}, {hap:5}, {pc:23}],
    "Crouch HP (hold)": [{c:20}, {hap:6}, {pc:21}],
    "Crouch LK": [{c:4}, {hap:3}, {pc:12}],
    "Crouch MK": [{c:8}, {hap:3}, {pc:18}],
    "Crouch HK": [{c:10}, {hap:3}, {pc:26}],
    "Crouch HK (hold)": [{c:22}, {hap:3}, {pc:23}],
    "Jump LP": [{c:3}, {hap:7}],
    "Jump MP": [{c:6}, {hap:4}],
    "Jump HP": [{c:9}, {hap:7}],
    "Jump HP (hold)": [{c:27}, {hap:6}],
    "Jump LK": [{c:4}, {hap:10}],
    "Jump MK": [{c:7}, {hap:8}],
    "Jump HK": [{c:9}, {hap:7}],
    "Jump HK (hold)": [{c:28}, {hap:6}],
    "Volare Combo": [{c:6}, {hap:2}, {c:9}, {hap:3}],
    "Caelum Arc": [{c:8}, {hap:9}],
    "Caelum Arc (hold)": [{c:27}, {hap:8}],
    "Novacula": [{c:9}, {hap:2}, {pc:20}],
    "Novacula Swipe": [{c:9}, {hap:2}, {pc:6}, {c:10}, {hap:2}, {pc:26}],
    "Novacula Thrust": [{c:9}, {hap:2}, {pc:6}, {c:10}, {hap:4}, {pc:23}], 
    "Malleus": [{c:20}, {hap:2}, {pc:21}],
    "Malleus (hold)": [{c:30}, {hap:2} , {pc:19}],
    "Malleus Breaker": [{c:20}, {hap:1}, {c:17}, {hap:2}, {pc:24}],
    "Magna Bunker": [{c:7}, {hap:2}, {pc:21}],
    "Magna Bunker (hold)": [{c:19}, {hap:2}, {pc:24}],
    "Knee": [{c:13}, {hap:4}, {pc:21}],
    "Knee (hold)": [{c:26}, {hap:4}, {pc:19}],
    "Falx Crusher": [{c:13}, {hap:3}, {c:15}, {hap:5}, {pc:25}],
    "Light Two Hitter": [{c:5}, {hap:1}, {c:13}, {hap:3}, {pc:22}],
    "Medium Two Hitter": [{c:6}, {hap:3}, {c:13}, {hap:2}, {pc:23}],
    "Heavy Two Hitter": [{c:11}, {hap:2}, {pc:2}, {c:23}, {hap:3}, {pc:19}],
    "Mounted Grace": [{c:4}, {hap:3}, {pc:23}],
    "Ponte Milvio": [{c:4}, {hap:3}, {pc:23}],
    "Drive Impact: Secutor": [{pcat:25}, {hap:2}, {pc:35}],
    "Drive Reversal: Love Tap": [{ip:19}, {hap:3}, {pc:31}],
    "Drive Parry": [{pcat:12}, {pc:33}],
    "Drive Rush": [{c:45}],
    "Taunt": [],
    "LP Gladius": [{c:4}, {pcat:6}, {c:6}, {hap:4}, {pc:21}],
    "LP Gladius (hold)": [{c:4}, {pcat:22}, {c:3}, {hap:4}, {pc:20}],
    "MP Gladius": [{c:4}, {pcat:8}, {c:6}, {hap:4}, {pc:21}],
    "MP Gladius (hold)": [{c:4}, {pcat:25}, {c:5}, {hap:4}, {pc:20}],
    "HP Gladius": [{c:4}, {pcat:11}, {c:6}, {hap:4}, {pc:21}],
    "HP Gladius (hold)": [{c:4}, {pcat:31}, {c:5}, {hap:4}, {pc:21}],
    "OD Gladius": [{pcat:16}, {hap:4}, {pc:21}],
    "OD Gladius (hold)": [{pcat:34}, {hap:4}, {pc:20}],
    "LP Dimachaerus": [{c:11}, {hap:4}, {pc:30}],
    "MP Dimachaerus": [{c:15}, {hap:4}, {pc:30}],
    "HP Dimachaerus": [{c:21}, {hap:4}, {pc:30}],
    "OD Dimachaerus": [{c:15}, {hap:4}, {pc:26}],
    "LP Dimachaerus Follow-up": [{c:11}, {hap:4}, {pc:6}, {c:12}, {hap:5}, {pc:23}],
    "MP Dimachaerus Follow-up": [{c:15}, {hap:4}, {pc:7}, {c:12}, {hap:5}, {pc:23}],
    "HP Dimachaerus Follow-up": [{c:21}, {hap:4}, {pc:9}, {c:17}, {hap:5}, {pc:23}],
    "OD Dimachaerus Follow-up": [{c:15}, {hap:4}, {pc:11}, {c:12}, {hap:5}, {pc:23}],
    "LP Phalanx": [{c:6}, {pcat:5}, {c:13}, {hap:3}, {pc:18}],
    "MP Phalanx": [{c:6}, {pcat:7}, {c:14}, {hap:3}, {pc:18}],
    "HP Phalanx": [{c:9}, {pcat:6}, {c:16}, {hap:3}, {pc:18}],
    "OD Phalanx": [{c:6}, {pcat:7}, {c:15}, {hap:3}, {pc:18}],
    "LK Quadriga": [{c:19}, {hap:4}, {pc:24}],
    "MK Quadriga": [{c:23}, {hap:4}, {pc:22}],
    "HK Quadriga": [{c:28}, {hap:4}, {pc:21}],
    "OD Quadriga": [{c:23}, {hap:4}, {pc:24}],
    "Scutum": [{c:2}, {pcat:26}, {pc:26}],
    "Scutum (absorb)": [{c:2}, {pcat:1}, {pc:6}, {hap:4}, {pc:20}],
    "OD Scutum": [{pcat:28}, {pc:29}],
    "OD Scutum (absorb)": [{pcat:7}, {hap:4}, {pc:20}],
    "Tonitrus 1": [{c:2}, {pcat:7}, {pc:14}, {hap:3}, {pc:24}],
    "Tonitrus 2": [{c:2}, {pcat:7}, {pc:14}, {hap:3}, {pc:19}, {hap:3}, {pc:36}],
    "Procella": [{c:2}, {pcat:7}, {pc:15}, {hap:3}, {pc:37}],
    "Enfold": [{c:2}, {pcat:6}, {pc:4}, {hap:3}, {pc:54}],
    "Javelin of Marisa": [{pcat:17}, {hap:5}, {pc:60}],
    "Javelin of Marisa (Hold)": [{pcat:27}, {pcat:17}, {hap:6}, {pc:60}],
    "Javelin of Marisa (Counter)": [{pcat:1}, {ip:5}, {hap:3}, {ip:1}, {pc:53}],
    "Meteorite": [{ip:8}, {hap:7}, {pc:33}, {hap:3}, {pc:59}],
    "Goddess of the Hunt": [{ip:12}, {hap:7}, {pc:60}],
    "Goddess of the Hunt (Critical Art)": [{ip:12}, {hap:7}, {pc:60}]
  }
}
export default data;