export default function MBison() {
  return ({
    "base": {
      "Stand LP": [],
      "Stand MP": [],
      "Stand HP": [],
      "Stand LK": [],
      "Stand MK": [],
      "Stand HK": [],
      "Crouch LP": [],
      "Crouch MP": [],
      "Crouch HP": [],
      "Crouch LK": [],
      "Crouch MK": [],
      "Crouch HK": [],
      "Jump LP": [],
      "Jump MP": [],
      "Jump HP": [],
      "Jump LK": [],
      "Jump MK": [],
      "Jump HK": [],
      "Hell Attack": [],
      "Psycho Hammer": [],
      "Evil Knee": [],
      "Hover Kick": [],
      "Shadow Hammer": [],
      "Shadow Spear": [],
      "Deadly Throw": [],
      "Death Tower": [],
      "Drive Impact: Hell Twist": [],
      "Drive Reversal: Hell Drive": [],
      "Drive Parry": [],
      "Drive Rush": [],
      "Taunt": [],
      "Psycho Mine Detonation": [],
      "LP Backfist Combo": [],
      "MP Backfist Combo": [],
      "HP Backfist Combo": [],
      "OD Backfist Combo": [],
      "LP Backfist Combo (bomb)": [],
      "MP Backfist Combo (bomb)": [],
      "HP Backfist Combo (bomb)": [],
      "OD Backfist Combo (bomb)": [],
      "LP Psycho Crusher": [],
      "MP Psycho Crusher": [],
      "HP Psycho Crusher": [],
      "OD Psycho Crusher": [],
      "LP Psycho Crusher (bomb)": [],
      "MP Psycho Crusher (bomb)": [],
      "HP Psycho Crusher (bomb)": [],
      "OD Psycho Crusher (bomb)": [],
      "LK Double Knee Press": [],
      "MK Double Knee Press": [],
      "HK Double Knee Press": [],
      "OD Double Knee Press": [],
      "Shadow Rise": [],
      "OD Shadow Rise": [],
      "Head Press": [],
      "OD Head Press": [],
      "Somersault Skull Diver": [],
      "Devil Reverse": [],
      "OD Devil Reverse": [],
      "Devil Reverse (bomb)": [],
      "OD Devil Reverse (bomb)": [],
      "Knee Press Nightmare": [],
      "Psycho Punisher": [],
      "Unlimited Psycho Crusher": [],
      "Unlimited Psycho Crusher (Critical Art)": []
    }
  })
}