const data = {
  "base": {
    "Stand LP": [{c:4}, {hap:3}, {pc:9}],
    "Stand MP": [{c:7}, {hap:3}, {pc:15}],
    "Stand HP": [{c:18}, {hap:3}, {pc:17}],
    "Stand LK": [{c:3}, {hap:2}, {pc:10}],
    "Stand MK": [{c:9}, {hap:4}, {pc:16}],
    "Stand HK": [{c:12}, {hap:4}, {pc:19}],
    "Crouch LP": [{c:3}, {hap:2}, {pc:10}],
    "Crouch MP": [{c:5}, {hap:3}, {pc:17}],
    "Crouch HP": [{c:9}, {hap:6}, {pc:21}],
    "Crouch LK": [{c:4}, {hap:2}, {pc:10}],
    "Crouch MK": [{c:7}, {hap:3}, {pc:19}],
    "Crouch HK": [{c:10}, {hap:3}, {pc:26}],
    "Jump LP": [{c:4}, {hap:4}],
    "Jump MP": [{c:7}, {hap:4}],
    "Jump HP": [{c:8}, {hap:6}],
    "Jump LK": [{c:4}, {hap:7}],
    "Jump MK": [{c:6}, {hap:7}],
    "Jump HK": [{c:9}, {hap:6}],
    "Hell Attack": [{c:7}, {hap:1}, {c:6}, {hap:4}],
    "Psycho Hammer": [{c:21}, {hap:3}, {pc:20}],
    "Evil Knee": [{c:9}, {hap:4}, {pc:17}],
    "Hover Kick": [{c:14}, {hap:10}, {pc:23}],
    "Shadow Hammer": [{c:7}, {hap:3}, {c:21}, {hap:3}, {pc:20}],
    "Shadow Spear": [{c:7}, {hap:3}, {c:15}, {hap:4}, {pc:20}],
    "Deadly Throw": [{c:4}, {hap:3}, {pc:23}],
    "Death Tower": [{c:4}, {hap:3}, {pc:23}],
    "Drive Impact: Hell Twist": [{pcat:25}, {hap:2}, {pc:35}],
    "Drive Reversal: Hell Drive": [],
    "Drive Parry": [{pcat:12}, {pc:33}],
    "Drive Rush": [{c:45}],
    "Taunt": [],
    "Psycho Mine Detonation": [],
    "LP Backfist Combo": [{c:12}, {hap:2}, {pc:10}, {hap:5}, {pc:25}],
    "MP Backfist Combo": [{c:16}, {hap:2}, {pc:10}, {hap:5}, {pc:26}],
    "HP Backfist Combo": [{c:21}, {hap:3}, {pc:10}, {hap:5}, {pc:20}],
    "OD Backfist Combo": [{c:13}, {hap:2}, {pc:19}, {hap:3}, {pc:23}, {hap:3}, {pc:44}],
    "LP Backfist Combo (bomb)": [],
    "MP Backfist Combo (bomb)": [],
    "HP Backfist Combo (bomb)": [],
    "OD Backfist Combo (bomb)": [],
    "LP Psycho Crusher": [{c:15}, {hap:16}, {pc:24}],
    "MP Psycho Crusher": [{c:19}, {hap:16}, {pc:24}],
    "HP Psycho Crusher": [{c:23}, {hap:26}, {pc:29}],
    "OD Psycho Crusher": [{c:12}, {pip:3}, {hap:16}, {pc:20}],
    "LP Psycho Crusher (bomb)": [],
    "MP Psycho Crusher (bomb)": [],
    "HP Psycho Crusher (bomb)": [],
    "OD Psycho Crusher (bomb)": [],
    "LK Double Knee Press": [{c:12}, {hap:2}, {pc:1}, {hap:2}, {pc:25}],
    "MK Double Knee Press": [{c:16}, {hap:2}, {pc:1}, {hap:2}, {pc:25}],
    "HK Double Knee Press": [{c:21}, {hap:2}, {pc:1}, {hap:2}, {pc:25}],
    "OD Double Knee Press": [{c:16}, {hap:2}, {pc:1}, {hap:2}, {pc:17}, {hap:3}, {pc:28}],
    "Shadow Rise": [{c:18}],
    "OD Shadow Rise": [{c:16}],
    "Head Press": [{c:15}, {hap:6}, {pc:26}],
    "OD Head Press": [{c:15}, {hap:4}, {pc:12}],
    "Somersault Skull Diver": [{pc:12}, {hap:10}, {pc:12}],
    "Devil Reverse": [{c:15}, {hap:21}, {pc:10}],
    "OD Devil Reverse": [{c:12}, {hap:13}, {pc:10}],
    "Devil Reverse (bomb)": [],
    "OD Devil Reverse (bomb)": [],
    "Knee Press Nightmare": [{pip:9}, {hap:2}, {pc:1}, {hap:3}, {pc:31}, {hap:2}, {pc:1}, {hap:2}, {pc:62}],
    "Psycho Punisher": [{ip:25}, {hap:7}, {pc:52}],
    "Unlimited Psycho Crusher": [{ip:9}, {hap:6}, {pc:65}],
    "Unlimited Psycho Crusher (Critical Art)": [{ip:9}, {hap:6}, {pc:65}]
  }
}
export default data;