const data = {
  "base": {
    "Stand LP": [],
    "Stand MP": [],
    "Stand HP": [],
    "Stand LK": [],
    "Stand MK": [],
    "Stand HK": [],
    "Crouch LP": [],
    "Crouch MP": [],
    "Crouch HP": [],
    "Crouch LK": [],
    "Crouch MK": [],
    "Crouch HK": [],
    "Jump LP": [],
    "Jump MP": [],
    "Jump HP": [],
    "Jump LK": [],
    "Jump MK": [],
    "Jump HK": [],
    "Blitz Strike": [],
    "Aerial Shot": [],
    "Run": [],
    "Backup": [],
    "Tempest Moon": [],
    "Tempest Moon (wind)": [],
    "Flapping Spin": [],
    "Beak Assault": [],
    "Crescent Kick": [],
    "Rising Kick": [],
    "Side Flip": [],
    "Front Flip": [],
    "Wall Jump": [],
    "Riding Glider": [],
    "Sunset Drop": [],
    "Desert Slider": [],
    "Drive Impact: Eagle Edge": [],
    "Drive Reversal: Eagle Slash": [],
    "Drive Parry": [],
    "Drive Rush": [],
    "Taunt": [],
    "LP Spinning Mixer": [],
    "LP Spinning Mixer (Wind)": [],
    "MP Spinning Mixer": [],
    "MP Spinning Mixer (Wind)": [],
    "HP Spinning Mixer": [],
    "HP Spinning Mixer (Wind)": [],
    "OD Spinning Mixer": [],
    "OD Spinning Mixer (Wind)": [],
    "LK Eagle Spike": [],
    "LK Eagle Spike (Wind)": [],
    "MK Eagle Spike": [],
    "MK Eagle Spike (Wind)": [],
    "HK Eagle Spike": [],
    "HK Eagle Spike (Wind)": [],
    "OD Eagle Spike": [],
    "OD Eagle Spike (Wind)": [],
    "Whirlwind Shot": [],
    "Whirlwind Shot (lvl 2)": [],
    "Whirlwind Shot (lvl 3)": [],
    "OD Whirlwind Shot": [],
    "OD Whirlwind Shot (Hold)": [],
    "LP Arabian Cyclone": [],
    "MP Arabian Cyclone": [],
    "HP Arabian Cyclone": [],
    "OD Arabian Cyclone": [],
    "Wing Stroke": [],
    "Rolling Assault": [],
    "Nail Assault": [],
    "LK Arabian Skyhigh": [],
    "MK Arabian Skyhigh": [],
    "HK Arabian Skyhigh": [],
    "OD Arabian Skyhigh": [],
    "Super Rashid Kick": [],
    "Ysaar": [],
    "Altair": [],
    "Altair (Critical Art)": []
  }
}
export default data;