const data = {
  "base": {
    "Stand LP": [{c:3}, {hap:2}, {pc:9}],
    "Stand MP": [{c:5}, {hap:3}, {pc:14}],
    "Stand HP": [{c:8}, {hap:3}, {pc:21}],
    "Stand LK": [{c:3}, {hap:3}, {pc:10}],
    "Stand MK": [{c:7}, {hap:3}, {pc:19}],
    "Stand HK": [{c:12}, {hap:8}, {pc:18}],
    "Crouch LP": [{c:4}, {hap:3}, {pc:7}],
    "Crouch MP": [{c:5}, {hap:4}, {pc:13}],
    "Crouch HP": [{c:11}, {hap:3}, {pc:23}],
    "Crouch LK": [{c:4}, {hap:3}, {pc:8}],
    "Crouch MK": [{c:6}, {hap:3}, {pc:18}],
    "Crouch HK": [{c:8}, {hap:3}, {pc:24}],
    "Jump LP": [{c:3}, {hap:5}],
    "Jump MP": [{c:8}, {hap:5}],
    "Jump HP": [{c:7}, {hap:4}, {pc:2}, {hap:3}],
    "Jump LK": [{c:4}, {hap:5}],
    "Jump MK": [{c:6}, {hap:6}],
    "Jump HK": [{c:7}, {hap:5}],
    "Blitz Strike": [{c:9}, {hap:5}],
    "Aerial Shot": [{c:7}, {hap:5}],
    "Run": [{ncar:18}],
    "Backup": [{ncar:18}, {c:7}, {hap:10}, {pc:17}],
    "Tempest Moon": [{ncar:18}, {c:15}, {hap:2}, {pc:4}, {hap:3}, {pc:21}],
    "Tempest Moon (wind)": [{ncar:18}, {c:8}, {hap:3}, {pc:21}, {hap:2}, {pc:3}, {hap:3}, {pc:22}],
    "Flapping Spin": [{c:7}, {hap:2}, {pc:14}, {hap:2}, {pc:18}],
    "Beak Assault": [{c:21}, {hap:3}, {pc:21}],
    "Crescent Kick": [{c:15}, {hap:4}, {pc:23}],
    "Rising Kick": [{c:5}, {hap:3}, {pc:12}, {hap:4}, {pc:36}],
    "Side Flip": [{c:32}],
    "Front Flip": [{c:69}],
    "Wall Jump": [{ncar:34}, {c:41}, {ncap:3}],
    "Riding Glider": [{c:4}, {hap:3}, {pc:23}],
    "Sunset Drop": [{c:4}, {hap:3}, {pc:23}],
    "Desert Slider": [{c:4}, {hap:3}],
    "Drive Impact: Eagle Edge": [{pcat:25}, {hap:2}, {pc:35}],
    "Drive Reversal: Eagle Slash": [{ip:19}, {hap:3}, {pc:31}],
    "Drive Parry": [{pcat:12}, {pc:33}],
    "Drive Rush": [{c:45}],
    "Taunt": [],
    "LP Spinning Mixer": [{c:7}, {hap:3}, {pc:5}, {hap:2}, {pc:4}, {hap:2}, {pc:24}],
    "LP Spinning Mixer (Wind)": [{c:5}, {hap:2}, {pc:4}, {hap:3}, {pc:3}, {hap:3}, {pc:4}, {hap:3}, {pc:3}, {hap:3}, {pc:4}, {hap:3}, {pc:3}, {hap:3}, {pc:4}, {hap:3}, {pc:3}, {hap:3}, {pc:15}], 
    "MP Spinning Mixer": [{c:7}, {hap:3}, {pc:2}, {hap:2}, {pc:5}, {hap:2}, {pc:3}, {hap:2}, {pc:48}],
    "MP Spinning Mixer (Wind)": [{c:4}, {hap:3}, {pc:2}, {hap:2}, {pc:4}, {hap:2}, {pc:3}, {hap:2}, {pc:6}, {hap:2}, {pc:3}, {hap:2}, {pc:5}, {hap:2}, {pc:3}, {hap:2}, {pc:5}, {hap:2}, {pc:3}, {hap:2}, {pc:56}],
    "HP Spinning Mixer": [{c:5}, {hap:2}, {pc:2}, {hap:3}, {pc:3}, {hap:3}, {pc:4}, {hap:3}, {pc:4}, {hap:3}, {pc:4}, {hap:3}, {pc:38}],
    "HP Spinning Mixer (Wind)": [{c:4}, {hap:2}, {pc:2}, {hap:3}, {pc:3}, {hap:2}, {pc:4}, {hap:3}, {pc:3}, {hap:3}, {pc:2}, {hap:3}, {pc:2}, {hap:3}, {pc:2}, {hap:3}, {pc:3}, {hap:3}, {pc:53}],
    "OD Spinning Mixer": [{ip:5}, {hap:3}, {pc:2}, {hap:3}, {pc:2}, {hap:4}, {pc:2}, {hap:4}, {pc:2}, {hap:4}, {pc:2}, {hap:4}, {pc:2}, {hap:4}, {pc:2}, {hap:3}, {pc:57}],
    "OD Spinning Mixer (Wind)": [{ip:4}, {hap:3}, {pc:2}, {hap:3}, {pc:2}, {hap:4}, {pc:2}, {hap:4}, {pc:2}, {hap:4}, {pc:2}, {hap:4}, {pc:2}, {hap:4}, {pc:2}, {hap:4}, {pc:2}, {hap:4}, {pc:2}, {hap:4}, {pc:55}],
    "LK Eagle Spike": [{c:14}, {hap:13}, {pc:31}],
    "LK Eagle Spike (Wind)": [{c:13}, {hap:13}, {pc:33}],
    "MK Eagle Spike": [{c:20}, {hap:13}, {pc:26}],
    "MK Eagle Spike (Wind)": [{c:16}, {hap:15}, {pc:50}],
    "HK Eagle Spike": [{c:25}, {hap:13}, {pc:27}],
    "HK Eagle Spike (Wind)": [{c:16}, {hap:15}, {pc:50}],
    "OD Eagle Spike": [{c:20}, {hap:13}, {pc:26}],
    "OD Eagle Spike (Wind)": [{c:6}, {pip:11}, {hap:14}, {pc:25}],
    "Whirlwind Shot": [{c:16}, {pat:36}],
    "Whirlwind Shot (lvl 2)": [{c:33}, {pat:36}],
    "Whirlwind Shot (lvl 3)": [{c:52}, {pat:36}],
    "OD Whirlwind Shot": [{c:16}, {pat:36}],
    "OD Whirlwind Shot (Hold)": [{c:44}, {pat:36}],
    "LP Arabian Cyclone": [{c:14}, {hap:3}, {pc:1}, {hap:15}, {pc:14}],
    "MP Arabian Cyclone": [{c:19}, {hap:3}, {pc:1}, {hap:15}, {pc:12}],
    "HP Arabian Cyclone": [{c:26}, {hap:3}, {pc:1}, {hap:15}, {pc:24}],
    "OD Arabian Cyclone": [{c:19}, {hap:3}, {pc:1}, {hap:26}],
    "Wing Stroke": [{c:14}, {hap:3}, {pc:1}, {hap:3}, {pc:67}],
    "Rolling Assault": [{c:14}, {hap:3}, {pc:1}, {hap:3}, {pc:33}],
    "Nail Assault": [{c:14}, {hap:3}, {pc:1}, {hap:3}, {pc:33}, {hap:3}, {pc:26}],
    "LK Arabian Skyhigh": [{c:12}, {hap:9}, {pc:46}],
    "MK Arabian Skyhigh": [{c:17}, {hap:9}, {pc:49}],
    "HK Arabian Skyhigh": [{c:20}, {hap:9}, {pc:57}],
    "OD Arabian Skyhigh": [{c:12}, {hap:9}, {pc:40}],
    "Super Rashid Kick": [{sip:8}, {hap:7}, {pc:76}],
    "Ysaar": [{c:10}, {pat:23}],
    "Altair": [{ip:10}, {hap:18}, {pc:82}],
    "Altair (Critical Art)": [{ip:10}, {hap:18}, {pc:82}]
  }
}
export default data;