const data = {
  "base": {
    "Stand LP": [],
    "Stand MP": [],
    "Stand HP": [],
    "Stand LK": [],
    "Stand MK": [],
    "Stand HK": [],
    "Crouch LP": [],
    "Crouch MP": [],
    "Crouch HP": [],
    "Crouch LK": [],
    "Crouch MK": [],
    "Crouch HK": [],
    "Jump LP": [],
    "Jump MP": [],
    "Jump HP": [],
    "Jump LK": [],
    "Jump MK": [],
    "Jump HK": [],
    "Collarbone Breaker": [],
    "Short Uppercut": [],
    "Solar Plexus Strike": [],
    "Axe Kick": [],
    "Whirlwind Kick": [],
    "Fuwa Triple Strike 1": [],
    "Fuwa Triple Strike 2": [],
    "High Double Strike": [],
    "Shoulder Throw": [],
    "Somersault Throw": [],
    "Drive Impact: Shingeki": [],
    "Drive Reversal: Chest Strike": [],
    "Drive Parry": [],
    "Drive Rush": [],
    "Taunt": [],
    "Denjin Charge": [],
    "LP Hadoken": [],
    "MP Hadoken": [],
    "HP Hadoken": [],
    "OD Hadoken": [],
    "Denjin Charge Hadoken": [],
    "OD Denjin Charge Hadoken": [],
    "LP Shoryuken": [],
    "MP Shoryuken": [],
    "HP Shoryuken": [],
    "OD Shoryuken": [],
    "LK Tatsumaki Senpukyaku": [],
    "MK Tatsumaki Senpukyaku": [],
    "HK Tatsumaki Senpukyaku": [],
    "OD Tatsumaki Senpukyaku": [],
    "Air Tatsumaki Senpukyaku": [],
    "OD Air Tatsumaki Senpukyaku": [],
    "LK High Blade Kick": [],
    "MK High Blade Kick": [],
    "HK High Blade Kick": [],
    "OD High Blade Kick": [],
    "LP Hashogeki": [],
    "MP Hashogeki": [],
    "HP Hashogeki": [],
    "OD Hashogeki": [],
    "Denjin Charge Hashogeki": [],
    "OD Denjin Charge Hashogeki": [],
    "Shinku Hadoken": [],
    "Denjin Hadoken": [],
    "Shin Hashogeki": [],
    "Denjin Hashogeki": [],
    "Shin Shoryuken": [],
    "Shin Shoryuken (Critical Art)": []
  }
}
export default data;