const data = {
  "base": {
    "Stand LP": [{c:3}, {hap:3}, {pc:7}],
    "Stand MP": [{c:5}, {hap:4}, {pc:11}],
    "Stand HP": [{c:9}, {hap:5}, {pc:18}],
    "Stand LK": [{c:4}, {hap:3}, {pc:11}],
    "Stand MK": [{c:8}, {hap:3}, {pc:18}],
    "Stand HK": [{c:11}, {hap:4}, {pc:20}],
    "Crouch LP": [{c:3}, {hap:2}, {pc:9}],
    "Crouch MP": [{c:5}, {hap:4}, {pc:13}],
    "Crouch HP": [{c:8}, {hap:6}, {pc:21}],
    "Crouch LK": [{c:4}, {hap:2}, {pc:10}],
    "Crouch MK": [{c:7}, {hap:3}, {pc:19}],
    "Crouch HK": [{c:8}, {hap:3}, {pc:23}],
    "Jump LP": [{c:3}, {hap:10}],
    "Jump MP": [{c:7}, {hap:5}],
    "Jump HP": [{c:8}, {hap:6}],
    "Jump LK": [{c:5}, {hap:10}],
    "Jump MK": [{c:6}, {hap:6}],
    "Jump HK": [{c:11}, {hap:8}],
    "Collarbone Breaker": [{c:19}, {hap:4}, {pc:19}],
    "Short Uppercut": [{c:6}, {hap:4}, {pc:25}],
    "Solar Plexus Strike": [{c:19}, {hap:5}, {pc:16}],
    "Axe Kick": [{c:3}, {hap:3}, {pc:7}],
    "Whirlwind Kick": [{c:3}, {hap:3}, {pc:7}],
    "Fuwa Triple Strike 1": [{c:5}, {hap:4}, {pc:2}, {c:4}, {hap:3}, {pc:16}],
    "Fuwa Triple Strike 2": [{c:5}, {hap:4}, {pc:2}, {c:4}, {hap:1}, {c:16}, {hap:4}, {pc:20}],
    "High Double Strike": [{c:9}, {hap:5}, {pc:2}, {c:8}, {hap:4}, {pc:20}],
    "Shoulder Throw": [{c:4}, {hap:3}, {pc:23}],
    "Somersault Throw": [{c:4}, {hap:3}, {pc:23}],
    "Drive Impact: Shingeki": [{pcat:25}, {hap:2}, {pc:35}],
    "Drive Reversal: Chest Strike": [{ip:19}, {hap:3}, {pc:31}],
    "Drive Parry": [{pcat:12},  {pc:33}],
    "Drive Rush": [{c:45}],
    "Taunt": [],
    "Denjin Charge": [{c:52}],
    "LP Hadoken": [{c:15}, {pat:32}],
    "MP Hadoken": [{c:13}, {pat:34}],
    "HP Hadoken": [{c:11}, {pat:36}],
    "OD Hadoken": [{c:11}, {pat:29}],
    "Denjin Charge Hadoken": [{c:11}, {pat:31}],
    "OD Denjin Charge Hadoken": [{c:11}, {pat:27}],
    "LP Shoryuken": [{c:4}, {hap:10}, {pc:33}],
    "MP Shoryuken": [{c:5}, {hap:10}, {pc:42}],
    "HP Shoryuken": [{c:6}, {hap:10}, {pc:49}],
    "OD Shoryuken": [{ip:5}, {hap:10}, {pc:52}],
    "LK Tatsumaki Senpukyaku": [{c:11}, {hap:3}, {pc:32}],
    "MK Tatsumaki Senpukyaku": [{c:13}, {hap:2}, {pc:13}, {hap:2}, {pc:31}],
    "HK Tatsumaki Senpukyaku": [{c:15 }, {hap:2}, {pc:13}, {hap:2}, {pc:13}, {hap:2}, {pc:31}],
    "OD Tatsumaki Senpukyaku": [{c:12}, {hap:2}, {pc:4}, {hap:2}, {pc:4}, {hap:2}, {pc:3}, {hap:2}, {pc:4}, {hap:2}, {pc:31}],
    "Air Tatsumaki Senpukyaku": [{c:10}, {hap:2}, {pc:5}, {hap:2}, {pc:6}, {hap:2}, {pc:27}],
    "OD Air Tatsumaki Senpukyaku": [{c:10}, {hap:2}, {pc:1}, {hap:3}, {pc:1}, {hap:3}, {pc:2}, {hap:3}, {pc:36}],
    "LK High Blade Kick": [{c:13}, {hap:6}, {pc:22}],
    "MK High Blade Kick": [{c:17}, {hap:9}, {pc:22}],
    "HK High Blade Kick": [{c:28}, {hap:9}, {pc:16}],
    "OD High Blade Kick": [{c:17}, {hap:5}, {pc:33}],
    "LP Hashogeki": [{c:11}, {hap:6}, {pc:18}],
    "MP Hashogeki": [{c:18}, {hap:6}, {pc:17}],
    "HP Hashogeki": [{c:29}, {hap:6}, {pc:19}],
    "OD Hashogeki": [{c:17}, {hap:6}, {pc:20}],
    "Denjin Charge Hashogeki": [{c:19}, {hap:6}, {pc:19}],
    "OD Denjin Charge Hashogeki": [{c:17}, {hap:6}, {pc:19}],
    "Shinku Hadoken": [{pip:6}, {pat:32}, {pc:48}],
    "Denjin Hadoken": [{pip:6}, {pat:32}, {pc:48}],
    "Shin Hashogeki": [{ip:11}, {hap:6}, {pc:39}],
    "Denjin Hashogeki": [{ip:11}, {hap:6}, {pc:39}],
    "Shin Shoryuken": [{ip:4}, {hap:12}, {pc:71}],
    "Shin Shoryuken (Critical Art)": [{ip:4}, {hap:12}, {pc:71}]
  }
}
export default data;