const data = {
  "base": {
    "Stand LP": [{c:3}, {hap:3}, {pc:7}],
    "Stand MP": [{c:6}, {hap:3}, {pc:16}],
    "Stand HP": [{c:8}, {hap:4}, {pc:18}],
    "Stand LK": [{c:4}, {hap:2}, {pc:12}],
    "Stand MK": [{c:8}, {hap:3}, {pc:18}],
    "Stand HK": [{c:11}, {hap:4}, {pc:21}],
    "Crouch LP": [{c:3}, {hap:3}, {pc:8}],
    "Crouch MP": [{c:3}, {hap:4}, {pc:14}],
    "Crouch HP": [{c:7}, {hap:6}, {pc:22}],
    "Crouch LK": [{c:4}, {hap:2}, {pc:11}],
    "Crouch MK": [{c:7}, {hap:3}, {pc:19}],
    "Crouch HK": [{c:10}, {hap:3}, {pc:23}],
    "Jump LP": [{c:3}, {hap:7}],
    "Jump MP": [{c:6}, {hap:4}],
    "Jump HP": [{c:8}, {hap:6}],
    "Jump LK": [{c:4}, {hap:7}],
    "Jump MK": [{c:6}, {hap:6}],
    "Jump HK": [{c:9}, {hap:7}],
    "Hammer Punch": [{c:21}, {hap:3}, {pc:19}],
    "Power Drive": [{c:6}, {hap:3}, {c:15}, {hap:3}, {pc:22}],
    "Power Shoot": [{c:6}, {hap:3}, {c:17}, {hap:3}, {pc:31}],
    "Power Dunk": [{c:6}, {hap:3}, {c:17}, {hap:3}, {pc:14}, {c:17}, {hap:3}, {pc:21}, {hap:6}, {pc:33}],
    "Fire Kick": [{c:7}, {hap:1}, {c:12}, {hap:2}, {pc:28}],
    "Passing Sway": [{c:6}, {hap:3}, {c:12}, {hap:2}, {pc:5}, {ip:21}, {pc:12}],
    "Passing Sway > Jumping Lariat": [{c:6}, {hap:3}, {c:12}, {hap:2}, {pc:5}, {ip:33}, {hap:2}, {pc:18}],
    "Passing Sway > Jumping Knee": [{c:6}, {hap:3}, {c:12}, {hap:2}, {pc:5}, {ip:33}, {hap:2}, {pc:20}],
    "Grasping Upper": [{c:4}, {hap:3}, {pc:23}],
    "Buster Throw": [{c:4}, {hap:3}, {pc:23}],
    "Drive Impact: Back Spin Kick": [{pcat:25}, {hap:2}, {pc:35}],
    "Drive Reversal: Back Knuckle": [],
    "Drive Parry": [{pcat:12}, {pc:33}],
    "Drive Rush": [{c:45}],
    "Taunt": [],
    "LP Power Wave": [{c:13}, {pat:36}],
    "MP Power Wave": [{c:15}, {pat:14}, {pc:19}],
    "HP Round Wave": [{c:28}, {pat:9}, {pc:16}],
    "OD Power Wave": [{c:14}, {pat:29}],
    "LP Quick Burn": [{c:9}, {hap:2}, {pc:10}, {hap:2}, {pc:23}],
    "OD Quick Burn": [{c:9}, {hap:2}, {pc:10}, {hap:2}, {pc:23}],
    "MP Burn Knuckle": [{c:13}, {hap:9}, {pc:20}],
    "HP Burn Knuckle": [{c:22}, {hap:14}, {pc:17}],
    "OD Burn Knuckle": [{c:18}, {hap:14}, {pc:17}],
    "LK Crack Shoot": [{c:15}, {hap:4}, {pc:18}],
    "MK Crack Shoot": [{c:16}, {hap:7}, {pc:18}],
    "HK Crack Shoot": [{c:22}, {hap:11}, {pc:19}],
    "OD Crack Shoot": [{c:19}, {hap:4}, {pc:19}],
    "LP Rising Tackle": [{c:4}, {hap:10}, {pc:33}],
    "MP Rising Tackle": [{c:5}, {hap:10}, {pc:40}],
    "HP Rising Tackle": [{c:6}, {hap:20}, {pc:42}],
    "OD Rising Tackle": [{ip:5}, {hap:15}, {pc:49}],
    "LK Power Charge": [{c:13}, {hap:5}, {pc:24}],
    "MK Power Charge": [{c:19}, {hap:6}, {pc:23}],
    "HK Power Charge": [{c:24}, {hap:9}, {pc:27}],
    "OD Power Charge": [{c:18}, {hap:8}, {pc:24}],
    "Buster Wolf": [{pip:6}, {hap:12}, {pc:60}],
    "Power Geyser": [{ip:12}, {pat:13}, {pc:54}],
    "Twin Geyser": [{ip:12}, {pat:1}, {ip:4}, {pc:30}, {pat:6}, {pc:43}],
    "Triple Geyser": [{ip:12}, {pat:1}, {ip:4}, {pc:30}, {pat:6}, {pc:11}, {ip:13}, {hap:1}, {ip:125}],
    "Rising Fang": [{ip:7}, {hap:27}, {pc:57}],
    "Rising Fang (Critical Art)": [{ip:7}, {hap:27}, {pc:57}]
  }
}
export default data;