export default function Zangief() {
  return ({
    "base": {
      "Stand LP": [],
      "Stand MP": [],
      "Stand HP": [],
      "Stand HP (hold)": [],
      "Stand LK": [],
      "Stand MK": [],
      "Stand HK": [],
      "Crouch LP": [],
      "Crouch MP": [],
      "Crouch HP": [],
      "Crouch LK": [],
      "Crouch MK": [],
      "Crouch HK": [],
      "Jump LP": [],
      "Jump MP": [],
      "Jump HP": [],
      "Jump LK": [],
      "Jump MK": [],
      "Jump HK": [],
      "Jump HK (hold)": [],
      "Flying Body Press": [],
      "Flying Headbutt": [],
      "Hellstab": [],
      "Knee Hammer": [],
      "Headbutt": [],
      "Cyclone Wheel Kick": [],
      "Smetana Dropkick": [],
      "Machine Gun Chops 1": [],
      "Machine Gun Chops 2": [],
      "Stomp": [],
      "Power Stomps 1": [],
      "Power Stomps 2": [],
      "Bodyslam": [],
      "German Suplex": [],
      "Capture Suplex": [],
      "Brain Buster": [],
      "Spinebuster": [],
      "Russian Drop": [],
      "Drive Impact: Double Russian Chop": [],
      "Drive Reversal: Reverse Russian Kick": [],
      "Drive Parry": [],
      "Drive Rush": [],
      "Taunt": [],
      "Double Lariat": [],
      "OD Double Lariat": [],
      "LP Screw Piledriver": [],
      "MP Screw Piledriver": [],
      "HP Screw Piledriver": [],
      "OD Screw Piledriver": [],
      "Borscht Dynamite": [],
      "OD Borscht Dynamite": [],
      "Russian Suplex (close)": [],
      "OD Russian Suplex (close)": [],
      "Siberian Express (near)": [],
      "OD Siberian Express (near)": [],
      "Siberian Express (far)": [],
      "OD Siberian Express (far)": [],
      "Tundra Storm": [],
      "Aerial Russian Slam": [],
      "Cyclone Lariat": [],
      "Cyclone Lariat (hold)": [],
      "Bolshoi Storm Buster": [],
      "Bolshoi Storm Buster (Critical Art)": []
    }
  })
}