const data = {
  "base": {
    "Stand LP": [{c:6}, {hap:3}, {pc:9}],
    "Stand MP": [{c:8}, {hap:4}, {pc:17}],
    "Stand HP": [{c:15}, {hap:3}, {pc:24}],
    "Stand HP (hold)": [{c:3}, {pcat:28}, {hap:3}, {pc:24}],
    "Stand LK": [{c:6}, {hap:2}, {pc:17}],
    "Stand MK": [{c:9}, {hap:4}, {pc:19}],
    "Stand HK": [{c:12}, {hap:4}, {pc:21}],
    "Crouch LP": [{c:5}, {hap:2}, {pc:8}],
    "Crouch MP": [{c:7}, {hap:3}, {pc:16}],
    "Crouch HP": [{c:10}, {hap:9}, {pc:35}],
    "Crouch LK": [{c:3}, {hap:3}, {pc:12}],
    "Crouch MK": [{c:8}, {hap:3}, {pc:18}],
    "Crouch HK": [{c:11}, {hap:3}, {pc:27}],
    "Jump LP": [{c:4}, {hap:7}],
    "Jump MP": [{c:7}, {hap:5}],
    "Jump HP": [{c:7}, {hap:4}],
    "Jump LK": [{c:4}, {hap:10}],
    "Jump MK": [{c:7}, {hap:8}],
    "Jump HK": [{c:9}, {hap:7}],
    "Jump HK (hold)": [{c:31}, {hap:6}],
    "Flying Body Press": [{c:8}, {hap:9}],
    "Flying Headbutt": [{c:7}, {hap:4}],
    "Hellstab": [{c:6}, {hap:3}, {pc:21}],
    "Knee Hammer": [{c:13}, {hap:7}, {pc:13}],
    "Headbutt": [{c:13}, {hap:5}, {pc:17}],
    "Cyclone Wheel Kick": [{c:21}, {hap:7}, {pc:25}],
    "Smetana Dropkick": [{c:15}, {hap:4}, {pc:40}],
    "Machine Gun Chops 1": [{c:8}, {hap:4}, {pc:20}, {hap:4}, {pc:20}],
    "Machine Gun Chops 2": [{c:8}, {hap:4}, {pc:20}, {hap:4}, {pc:20}, {hap:4}, {pc:32}],
    "Stomp": [{c:8}, {hap:3}, {pc:17}],
    "Power Stomps 1": [{c:8}, {hap:3}, {pc:15}, {hap:3}, {pc:19}],
    "Power Stomps 2": [{c:8}, {hap:4}, {pc:15}, {hap:3}, {pc:16}, {hap:3}, {pc:24}],
    "Bodyslam": [{c:4}, {hap:3}, {pc:23}],
    "German Suplex": [{c:4}, {hap:3}, {pc:23}],
    "Capture Suplex": [{c:4}, {hap:3}, {pc:23}],
    "Brain Buster": [{c:4}, {hap:3}, {pc:23}],
    "Spinebuster": [{c:4}, {hap:3}, {pc:23}],
    "Russian Drop": [{c:4}, {hap:3}, {pc:23}],
    "Drive Impact: Double Russian Chop": [{pcat:25}, {hap:2}, {pc:35}],
    "Drive Reversal: Reverse Russian Kick": [{ip:19}, {hap:3}, {pc:31}],
    "Drive Parry": [{pcat:12}, {pc:33}],
    "Drive Rush": [{c:45}],
    "Taunt": [],
    "Double Lariat": [{c:5}, {pip:9}, {hap:2}, {pip:3}, {hap:2}, {pip:4}, {hap:2}, {pip:8}, {hap:2}, {pip:6}, {hap:2}, {pc:27}],
    "OD Double Lariat": [{pip:11}, {hap:2}, {pip:1}, {hap:3}, {pip:3}, {hap:2}, {pip:6}, {hap:2}, {pip:4}, {hap:2}, {pc:26}],
    "LP Screw Piledriver": [{c:4}, {hap:3}, {pc:54}],
    "MP Screw Piledriver": [{c:4}, {hap:3}, {pc:54}],
    "HP Screw Piledriver": [{c:4}, {hap:3}, {pc:54}],
    "OD Screw Piledriver": [{c:4}, {hap:3}, {pc:54}],
    "Borscht Dynamite": [{c:3}, {hap:3}, {pc:44}],
    "OD Borscht Dynamite": [{c:3}, {hap:3}, {pc:44}],
    "Russian Suplex (close)": [{c:9}, {hap:2}, {pc:50}],
    "OD Russian Suplex (close)": [{c:9}, {hap:2}, {pc:50}],
    "Siberian Express (near)": [{c:27}, {hap:2}, {pc:41}],
    "OD Siberian Express (near)": [{c:27}, {hap:2}, {pc:44}],
    "Siberian Express (far)": [{c:10}, {pcat:44}, {hap:2}, {pc:40}],
    "OD Siberian Express (far)": [{c:2}, {pcat:52}, {hap:2}, {pc:40}],
    "Tundra Storm": [{c:5}, {pcat:50}, {pc:24}],
    "Aerial Russian Slam": [{ip:10}, {hap:7}, {pc:60}],
    "Cyclone Lariat": [{ip:17}, {hap:91}, {pip:8}, {hap:3}, {pc:52}],
    "Cyclone Lariat (hold)": [{ip:17}, {hap:94}, {pip:8}, {hap:3}, {pc:52}],
    "Bolshoi Storm Buster": [{ip:6}, {hap:1}, {pc:116}],
    "Bolshoi Storm Buster (Critical Art)": [{ip:6}, {hap:1}, {pc:116}]
  }
}
export default data;